In [1]:
import pandas as pd
# Show all columns
pd.set_option("display.max_columns", None)
# from scipy.stats import chi2_contingency

In [58]:
# import os

# file_path = "/Users/aca/Desktop/ACA_Artashes/data_analytics_with_python/data/raw/deaf_dataset/deaf_data_sheet.xlsx"

# print(os.path.exists(file_path))

In [59]:
# df = pd.read_excel("deaf_data_sheet.xlsx")

In [2]:
df = pd.read_excel(
    "../data/raw/deaf_dataset/deaf_data_sheet.xlsx",
)

In [3]:
df.head()

,Unnamed: 0,Timestamp,Հարցազրուցավարի անուն ազգանուն,Հարցազրույցը իրականացվել է՝,Հարցվողի անուն ազգանուն,Հարցազրույցի ամսաթիվ,A1. Նշե՛ք Ձեր մարզը:,A2. Նշեք Ձեր բնակավայրի տիպը:,A3. Նշեք Ձեր բնակավայրի/վարչական շրջանի անունը:,A4. Հարցվողի սեռը:,"A5. Նշե՛ք, խնդրեմ, Ձեր տարիքը:",A6. Նշե՛ք Ձեր ամուսնական կարգավիճակը,A7. Ու՞մ հետ եք բնակվում:,A8. Ձեզ հետ բնակվող ընտանիքի անդամներից ովքե՞ր ունեն լսողության խնդիրներ:,A9. Դուք Ձեզ համարում եք՝,A10. Առողջության բաղադրիչների վերաբերյալ դժվարություններ ունե՞ք: [Տեսողություն],"A10. Առողջության բաղադրիչների վերաբերյալ դժվարություններ ունե՞ք: [Հենաշարժողական վիճակ /քայլել, վազել/]",A10. Առողջության բաղադրիչների վերաբերյալ դժվարություններ ունե՞ք: [Հիշողություն և կենտրոնացում],A10. Առողջության բաղադրիչների վերաբերյալ դժվարություններ ունե՞ք: [Խոսելու կարողություն],A10. Առողջության բաղադրիչների վերաբերյալ դժվարություններ ունե՞ք: [Ինքնախնամքի՝ ինքնուրույն հագնվելիս կամ լվացվելիս/լոգանք ընդունելիս դժվարություններ/Ինքնուրույն հագնվելիս կամ լվացվելիս/լոգանք ընդունելիս],"A11. Նշված տարբերակներից, ո՞րն է առավել լավ բնութագրում Ձեր իրավիճակը:",A13. Հետևյալ աջակցող միջոցներից որո՞նք եք կրում:,A14. Ու՞մ միջոցով եք ձեռք բերել Ձեր աջակցող միջոցը /իմպլանտը կամ սարքը/:,A15. Որքանո՞վ եք գոհ Ձեր աջակցող միջոցից կամ սարքից:,A16. Որքան հաճախ եք կիրառում հաղորդակցության հետևյալ ձևերից յուրաքանչյուրը: [Շուրթերից կարդալը],A16. Որքան հաճախ եք կիրառում հաղորդակցության հետևյալ ձևերից յուրաքանչյուրը: [Ժեստերով հաղորդկացվելը],A16. Որքան հաճախ եք կիրառում հաղորդակցության հետևյալ ձևերից յուրաքանչյուրը: [Բանավոր շփումը ինքնուրույն],A16. Որքան հաճախ եք կիրառում հաղորդակցության հետևյալ ձևերից յուրաքանչյուրը: [Գրավոր շփումը],"A17. ԱՐՑՆԵԼ ՄԻԱՅՆ ԵԹԵ ՆԱԽՈՐԴ ՀԱՐՑՈՒՄ ՆՇԵԼ Է, ՈՐ ՀԱՂՈՐԴԱԿՑՎՈՒՄ Է ԺԵՍՏԵՐԻ ԼԵԶՎՈՎ Ընդհանուր առմամբ, որքանո՞վ եք գոհ ժեստերի լեզվի թարգմանիչների աշխատանքից:",Որքանով եք գոհ Ձեր անցած խոսքային թերապիայից:,B1. Հետևյալ կարողություններից և հմտություններից որոնց եք տիրապետում և ինչ չափով: [Մարդկանց հետ հաղորդակցվելու հմտություններ],B1. Հետևյալ կարողություններից և հմտություններից որոնց եք տիրապետում և ինչ չափով: [Սնունդ պատրաստելու հմտություններ],B1. Հետևյալ կարողություններից և հմտություններից որոնց եք տիրապետում և ինչ չափով: [Հիգիենային հետևելու հմտություններ],B1. Հետևյալ կարողություններից և հմտություններից որոնց եք տիրապետում և ինչ չափով: [Մեքենա վարելու հմտություններ],B1. Հետևյալ կարողություններից և հմտություններից որոնց եք տիրապետում և ինչ չափով: [Ժամանակի կառավարման հմտություններ],B1. Հետևյալ կարողություններից և հմտություններից որոնց եք տիրապետում և ինչ չափով: [Ձեր առօրյան պլանավորելու հմտություններ],B1. Հետևյալ կարողություններից և հմտություններից որոնց եք տիրապետում և ինչ չափով: [Նպատակադրման հմտություններ],B1. Հետևյալ կարողություններից և հմտություններից որոնց եք տիրապետում և ինչ չափով: [Ձեր ծախսերը պլանավորելու հմտություններ],B1. Հետևյալ կարողություններից և հմտություններից որոնց եք տիրապետում և ինչ չափով: [Բանկային համակարգից օգտվելու հմտություններ],B1. Հետևյալ կարողություններից և հմտություններից որոնց եք տիրապետում և ինչ չափով: [Օնլայն վճարումներ կատարելու հտություններ],B2. Ինչպես կգնահատեք գրելու Ձեր կարողությունը:,B3. Ինչպես կգնահատեք կարդալու Ձեր կարողությունը:,B4. Որքանո՞վ եք տիրապետում հետևյալ օտար լեզուներից յուրաքանչյուրին. [Ռուսերեն],B4. Որքանո՞վ եք տիրապետում հետևյալ օտար լեզուներից յուրաքանչյուրին. [Անգլերեն],B4. Որքանո՞վ եք տիրապետում հետևյալ օտար լեզուներից յուրաքանչյուրին. [Այլ],B5. Նշված տարբերակներից որը կլիներ հեռուստատեսային հաղորդումները մատչելի դարձնելու Ձեզ ամենահարմար տարբերակը,B6. Ստորև թվարկված հարմարեցումներից որոնց կարիքը ունեք:\t [Սղագրողների առկայություն],B6. Ստորև թվարկված հարմարեցումներից որոնց կարիքը ունեք:\t [Աջակցող լսողական սարք],B6. Ստորև թվարկված հարմարեցումներից որոնց կարիքը ունեք:\t [Տեքստային հաղորդակցում],B6. Ստորև թվարկված հարմարեցումներից որոնց կարիքը ունեք:\t [Լուսագրերով տեսանյութեր],B6. Ստորև թվարկված հարմարեցումներից որոնց կարիքը ունեք:\t [ՀԺԼ թարգմանություն],B7. Ունե՞ք ինքնակենսագրական (CV (սիվի) կամ ռեզյումե):,"B8. Ասացե՛ք խնդրեմ, ստորև թվարկվածներից E5. Ասացե՛ք խնդրեմ, որքանո՞վ եք ծանոք ստորև թվարկված իրավական կարգավորումներին: [Հաշմանդամություն ունեցող անձանց իրավունքների մասին ՄԱԿ-ի կոնվենցիա]","B8. Ասացե՛ք խնդրեմ, ստորև թվարկվածներից E5. Ասացե՛ք խնդրեմ, որքանո՞վ եք ծանոք ստորև թվարկված իրավական կարգավորումներին: [Հաշմանդամություն ունեցող անձանց իրավունքների մասին օրենք, ընդունված 2021 թվականին]","B9. Ձեր իրավունքների ոտնահարման դեպքում, նշված տարբերակներից որի՞ն եք երբևէ դիմել: [Մարդու իրավունքների պաշտպանի գրասենյակ]","B9. Ձեր իրավունքների ոտնահարման դեպքում, նշված տարբերակներից որի՞ն եք երբևէ դիմել: [Որևէ Հասարակական կազմակերպություն]","B9. Ձեր իրավունքների ոտնահարման դեպքում, նշված տարբերակներից որի՞ն եք երբևէ դիմել: [Իրավաբանի]","B9. Ձեր իրավունքների ոտնահարման դեպքում, նշված տարբերակներից որի՞ն եք երբևէ դիմել: [Այլ]",B10. Ինչ հաճախականությամբ եք կատարում հետևյալ գործողություններից յուրաքանչյուրը: [Տանը կամ այգում մարմնամարզություն կատարել],B10. Ինչ հաճախականությամբ եք կատարում հետևյալ գործողություններից յուրաքանչյուրը: [Սպորտային խմբակ հաճախել],B10. Ինչ հաճախականությամբ եք կատարում հետևյալ գործողություններից յուրաքանչյուրը: [Մարզասրահ հաճախել],B10. Ինչ հաճախականությամբ եք կատարում հետևյալ գործողություններից յուրաքանչյուրը: [Թատրոն գնալ],B10. Ինչ հաճախականությամբ եք կատարում հետևյալ գործողություններից յուրաքանչյուրը: [Կինո գնալ],B10. Ինչ հաճախականությամբ եք կատարում հետևյալ գործողություններից յուրաքանչյուրը: [Տանը կինո նայել],B10. Ինչ հաճախականությամբ եք կատարում հետևյալ գործողություններից յուրաքանչյուրը: [Մասնակցել Ձեր համայնքի ավագանու նիստերին],B10. Ինչ հաճախականությամբ եք կատարում հետևյալ գործողություններից յուրաքանչյուրը: [Մասնակցել համայնքային քննարկումներին],B10. Ինչ հաճախականությամբ եք կատարում հետևյալ գործողություններից յուրաքանչյուրը: [Մասնակցել համայնքային շաբաթօրյակների],B11. Ո՞րքանով եք ինքնուրույն կայացնում Ձեր կյանքի հետևյալ ոլորտների վերաբերյալ որոշումները: [Աշխատելու վերաբերյալ որոշումները],B11. Ո՞րքանով եք ինքնուրույն կայացնում Ձեր կյանքի հետևյալ ոլորտների վերաբերյալ որոշումները: [Անձնական կյանքի վերաբերյալ որոշումները],B11. Ո՞րքանով եք ինքնուրույն կայացնում Ձեր կյանքի հետևյալ ոլորտների վերաբերյալ որոշումները: [Ընկերների վերաբերյալ որոշումները],B11. Ո՞րքանով եք ինքնուրույն կայացնում Ձեր կյանքի հետևյալ ոլորտների վերաբերյալ որոշումները: [Ֆինանսական ծախսերի վերաբերալ որոշումները],B11. Ո՞րքանով եք ինքնուրույն կայացնում Ձեր կյանքի հետևյալ ոլորտների վերաբերյալ որոշումները: [Ժամանցի վերաբերյալ որոշումները],C1. Ո՞րն է Ձեր կրթական աստիճանը:,C1. որ թվականներին եք սովորել դպրոցում:,C2. Որքանո՞վ է դպրոցում դասավանդող ուսուցիչների բանավոր խոսքը Ձեզ համար մատչելի:,C4. Ինչպե՞ս կգնահատեք ուսուցիչների հետ Ձեր հաղորդակցությունը:,"C5. Արդյոք ունե՞ք ընտրության հնարավորություն, հանձնարարությունը ներկայացնել Ձեզ համար մատչելի եղանակով:",C6. Ինչպե՞ս կգնահատեք դպրոցի հետևյալ մասնագետների աշխատանքի արդյունավետությունը: [Հատուկ մանկավարժ],C6. Ինչպե՞ս կգնահատեք դպրոցի հետևյալ մասնագետների աշխատանքի արդյունավետությունը: [Սոցիալական աշխատող],C6. Ինչպե՞ս կգնահատեք դպրոցի հետևյալ մասնագետների աշխատանքի արդյունավետությունը: [Հոգեբան],"C7. Ընդհանուր առմամբ, ինչպիսի՞ն է տվյալ ուսումնական հաստատության ուսուցիչների վերաբերմունքը Ձեր հանդեպ.",C8. Հետևյալ տարբերակներից ո՞րն է առավել լավ բնութագրում Ձեր՝ Ձեր համադասարանցիների հետ ունեցած հարաբերությունները.,C9. Կուզեի՞ք որ դպրոցում աշակերտները սովորեին ժեստերի լեզու:,"C10. ՀԱՐՑՆԵԼ ՄԻԱՅՆ ԱՅՆ ԴԵՊՔՈՒՄ, ԵԹԵ ԴՊՐՈՑԱԿԱՆ ԿՐԹՈՒԹՅՈՒՆԸ ՀԱՄԸՆԿԵԼ Է ՔՈՎԻԴԻ ԺԱՄԱՆԱԿԱՀԱՏՎԱԾԻ ՀԵՏ: Ինչպե՞ս է ազդել COVID-19 համավարակի ժամանակ հեռավար կրթության անցնելը Ձեր սովորելու արդյունավետության վրա:","C11. Ասացե՛ք, խնդրեմ, թե որ թվականներին եք սովորել տվյալ ուսումնական հաստատությունում:",C12. Որքանո՞վ է տվյալ ուսումնական հաստատությունում դասավանդող դասախոսների բանավոր խոսքը Ձեզ համար մատչելի:,"C13. Արդյո՞ք դասախոսը դասը պատմելիս, կամ որպես օժանդակ նյութ Ձեզ տրամադրում է ուսումնական տեսանյութեր:",C14. Արդյո՞ք ուսուցիչների կողմից տրամադրված տեսանյութերը լուսագրերով են:,"C15. Ընդհանուր առմամբ, որքանո՞վ են տվյալ ուսումնական հաստատությունում դասավանդող դասախոսները պատրաստակամ անհատական մոտեցում ցուցաբերել սովորողին:",C16. Ինչպե՞ս կգնահատեք տվյալ ուսումնական հաստատությունում դասավանդող դասախոսների հետ Ձեր հաղորդակցությունը:,"C17. Արդյոք ունե՞ք ընտրության հնարավորություն, քննությունը հանձնել Ձեզ համար մատչելի եղանակով /գրավոր քննություն կամ բանավոր քննություն/:",C18. Ինչպե՞ս կգնահատեք դեկանատի աշխատակիցների հետ հաղորդակցվելու արդյունավետությունը:,"C19. Որքանո՞վ է տվյալ ուսումնական հաստատության տարածքը հարմար, լսողության խնդիրներ ունեցող անձանց համար վիզուալ կողմնորոշվելու տեսանկյունից (ցուցանակների առկայություն, համարակալումներ և այլն)","C20. Ընդհանուր առմամբ, ինչպիսի՞ն է տվյալ ուսումնական հաստատության դասախոսների վերաբերմունքը Ձեր հանդեպ.",C21. Հետևյալ տարբերակներից ո՞րն է առավել լավ բնութագրում Ձեր կուրսեցիների հետ ունեցած հարաբերությունները.,"C22. ՀԱՐՑՆԵԼ ՄԻԱՅՆ ԱՅՆ ԴԵՊՔՈՒՄ, ԵԹԵ ՆԱԽՆԱԿԱՆ, ՄԻՋԻՆ ՄԱՍՆԱԳԻՏԱԿԱՆ ԵՎ ԲԱՐՁՐԱԳՈՒՅՆ ԿՐԹՈՒԹՅՈՒՆԸ ՀԱՄԸՆԿԵԼ Է ՔՈՎԻԴԻ ԺԱՄԱՆԱԿԱՀԱՏՎԱԾԻ ՀԵՏ: Ինչպե՞ս է ազդել COVID-19 համավարակի ժամանակ հեռավար կրթության անցնելը Ձեր սովորելու արդյունավետության վրա:",Unnamed: 96,D1. Նշեք Ձեր հիմնական զբաղվածությունը.,D2. Որո՞նք են աշխատանք չփնտրելու պատճառները:,D3. Ինչպե՞ս եք փորձում գտնել աշխատանք (Կարող եք նշել 1-ից ավելի տարբերակ):,D4. Տեղյա՞կ եք արդյոք միասնական սոցիալական ծառայության (նախկինում՝ զբաղվածության պետական գործակալություն) մասին:,D5. Երբևէ դիմե՞լ եք միասնական սոցիալական ծառայություն (նախկինում զբաղվածության գործակալություն) աշխատանք գտնելու հարցով:,D6. Հաջողվե՞լ է միասնական սոցիալական ծառայությանը (նախկինում զբաղվածության գործակալություն) Ձեզ համար աշխատանք գտնել:,D7. Ձեր աշխատանքը՝,"D8. Նշե՛ք այն աշխատանքը, որը Դուք ներկա պահին կատարում եք",D9. Արդյո՞ք Ձեր ներկայիս աշխատանքը համապատասխանում է Ձեր մասնագիտական կրթությանը:,D10. Ինչպե՞ս եք գտել Ձեր ներկայիս աշխատանքը:,D11. Որքա՞ն ժամանակ է որ կատարում եք Ձեր աշխատանքը,D12. Ձեր աշխատանքային գրաֆիկը՝,D13. Օրական միջինում քանի՞ ժամ եք աշխատում ՝,D14. Ամսվա մեջ միջինում քանի՞ օր եք աշխատում՝,D15. Ինչպե՞ս կգնահատեք գործատուի հետ Ձեր հաղորդակցության արդյունավետությունը:,D16. Ինչպե՞ս կգնահատեք Ձեր գործընկերների/մյուս աշխատակիցների հետ Ձեր հաղորդակցության արդյունավետությունը:,D17. Գիտե՞ք արդյոք Ձեր աշխատանքային իրավունքների մասին:,"D18. Ըստ Ձեզ, որքանո՞վ են Ձեր աշխատանքային իրավունքները պաշտպանված Ձեր աշխատավայրում:",D19. Ունե՞ք արդյոք աշխատանքային պայմանագիր:,D20. Ինչպիսի՞ն է գործատուի վերաբերմունքը Ձեր հանդեպ:,D21. Ինչպիսի՞ն է Ձեր գործընկերների/մյուս աշխատակիցների վերաբերմունքը Ձեր հանդեպ.,D22. Ո՞րն է Ձեր երազանքի աշխատանքը,D23. Արդյոք դուք կամ Ձեր ընտանիքի անդամներից մեկը կորցրե՞լ է իր աշխատանքը COVID-19 համավարակի հետևանքով:,D24. Արդյո՞ք Դուք կամ Ձեր ընտանիքի անդամներից մեկը առողջական խնդիրներ է ձեռք բերել/վիրավորվել կամ զոհվել է 44 օրյա պատերազմի հետևանքով:,D25. Ինչպիսի՞ սոցիալական ապահովություն եք ստանում:,"E1. Որքանո՞վ եք ինքնուրույն այցելում առողջապահական հաստատություններ, Ձեզ անհրաժեշտ բժշկական ծառայություններից օգտվելու համար:","E2. Սովորաբար, ինչպե՞ս եք հաղորդակցվում բժիշկների հետ:","E3. Ասացե՛ք, խնդրեմ, ընդհանուր առմամբ, որքանով է Ձեր և բժիկների միջև հաղորդակցությունը արդյունավետ:",E4. Օգտվել կամ օգտվու՞մ եք արդյոք որևէ բժշկական ծառայությունից անվճար:,E5. Ո՞ր ծառայությունից/ծառայություններից եք անվճար օգտվում:,E6. Երբևէ դիմե՞լ եք հոգեբանի:,E7. Ունե՞ք արդյոք հոգեբանի ծառայության կարիք:,Նշումների համար,"C3. Ընդհանուր առմամբ, որքանո""վ են ուսուցիչները պատրաստակամ անհատական մոտեցում ցուցաբերել աշակերտին:",Հարցազրույցը իրականացվել է՝.1
0,1,2022-05-29 19:05:36.394,Անահիտ Դալալյան,NaN,Անգելինա Քառյան,2022-05-29 00:00:00,Լոռի,Քաղաք,Վանաձոր,Իգական,23,"4. Ամուսնացած չեմ, չունեմ զուգընկեր",Մայր,Ոչ մեկը,Խուլ,Ընդհանրապես չունեմ,Ընդհանրապես չունեմ,Ընդհանրապես չունեմ,Շատ դժվարություններ ունեմ,Ընդհանրապես չունեմ,Ունեցել եմ խոսքի խնդիր և դիմել եմ խոսքային թեր...,Լսողական սարք երկկողմանի կրել է մինչև 17 տարեկ...,"Չգիտեմ, մայրս է զբաղվել այդ հարցով:","Այն ժամանակ կրելուց դժգոհ եմ եղել հարմար չէր, ...",Հաճախ,Միշտ,Հաճախ,Հաճախ,Շատ գոհ եմ,Շատ գոհ եմ,Շատ լավ,"Ոչ լավ, ոչ վատ",Շատ լավ,"Ոչ լավ, ոչ վատ","Ոչ լավ, ոչ վատ",Լավ,"Ոչ լավ, ոչ վատ",Լավ,"Ոչ լավ, ոչ վատ",Վատ,3. Բավարար,3. Բավարար,Ավելի շուտ չեմ տիրապետում,Ավելի շուտ չեմ տիրապետում,NaN,1. Ժեստերի լեզվի թարգմանություն,Ընդհանրապես անհրաժեշտ չէ,Ավելի շուտ անհրաժեշտ չէ,Ավելի շուտ անհրաժեշտ է,Ավելի շուտ անհրաժեշտ չէ,Շատ անհրաժեշտ է,"3. Չգիտեմ, թե դա ինչ է",Ընդհանրապես չեմ լսել,Որոշ չափով տեղյակ եմ,"Ոչ, չեմ դիմել","Ոչ, չեմ դիմել","Ոչ, չեմ դիմել",NaN,Միշտ,Պարբերաբար,Պարբերաբար,Երբեմն,Երբեք,Երբեք,Երբեք,Երբեք,Երբեմն,Հիմնականում ինքնուրույն եմ,Հիմնականում ինքնուրույն եմ,Հիմնականում ինքնուրույն եմ,Հիմնականում ինքնուրույն եմ,Հիմնականում ինքնուրույն չեմ,Մասնավոր ուսումնական կենտրոն,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"5. Գործազուրկ, որը փնտրում է աշխատանք ԱՆՑՈՒՄ D3",NaN,1. Ծանոթների միջոցով,2. Ոչ,2. Ոչ ԱՆՑՈՒՄ D7,NaN,Այս պահին չեմ աշխատում,Այս պահին չեմ աշխատում,Այս պահին չեմ աշխատում,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"2. Այո, որոշ չափով գիտեմ իմ աշխատանքային իրավո...",NaN,NaN,NaN,NaN,Մատնահարդար լինելը,2. Ոչ,3. Ոչ,2. Հաշմանդամության թոշակ,3. Հիմնականում այցելում եմ օգնականի ուղեկցությամբ,"Օգնականի ուղեկցությամբ, իսկ մենակով գնալու դեպ...",2. Հաղորդակցվում ենք հիմնականում առանց դժվարու...,3. Դժվարանում եմ պատասխանել,NaN,2. Ոչ,2. Ոչ,NaN,NaN,NaN
1,2,2022-05-30 22:16:40.892,Անահիտ Դալալյան,NaN,Անահիտ Ղաբուզյան,2022-05-30 00:00:00,Լոռի,Քաղաք,Վանաձոր,Իգական,51,"1. Ամուսնացած եմ, չունեմ երեխաներ",Ամուսին/Կին,Ամուսին/Կին,Խուլ,Որոշ չափով ունեմ,Ընդհանրապես չունեմ,Որոշ չափով ունեմ,Ընդհանրապես չեմ կարողանում,Ընդհանրապես չունեմ,"Ունեցել եմ խոսքի խնդիր, սակայն չեմ դիմել խոսքա...",Լսողական սարք չեմ կրում,NaN,NaN,Երբեմն,Միշտ,Երբեմն,Երբեմն,Շատ գոհ եմ,NaN,"Ոչ լավ, ոչ վատ",Շատ լավ,Շատ լավ,Բացակայում է,Լավ,Լավ,"Ոչ լավ, ոչ վատ",Լավ,Լավ,Բացակայում է,3. Բավարար,3. Բավարար,Ավելի շուտ չեմ տիրապետում,Ընդհանրապես չեմ տիրապետում,NaN,1. Ժեստերի լեզվի թարգմանություն,Ընդհանրապես անհրաժեշտ չէ,Ընդհանրապես անհրաժեշտ չէ,Ընդհանրապես անհրաժեշտ չէ,Ընդհանրապես անհրաժեշտ չէ,Շատ անհրաժեշտ է,"3. Չգիտեմ, թե դա ինչ է",Ընդհանրապես չեմ լսել,Ընդհանրապես չեմ լսել,"Ոչ, չեմ դիմել","Ոչ, չեմ դիմել","Ոչ, չեմ դիմել",NaN,Երբեք,Երբեք,Երբեք,Երբեք,Երբեմն,Միշտ,Երբեք,Երբեք,Երբեք,Ամբողջովին ինքնուրույն եմ,Ամբողջովին ինքնուրույն եմ,Ամբողջովին ինքնուրույն եմ,Հիմնականում ինքնուրույն չեմ,Ամբողջովին ինքնուրույն եմ,Հիմնական հանրակրթական դպրոց,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"5. Գործազուրկ, որը փնտրում է աշխատանք ԱՆՑՈՒՄ D3",NaN,1. Ծանոթների միջոցով,2. Ոչ,NaN,NaN,NaN,NaN,4. Մասնագիտական կրթություն չունեմ,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"2. Այո, որոշ չափով գիտեմ իմ աշխատանքային իրավո...",NaN,NaN,NaN,NaN,Մաքրություն անել եմ սիրում:,2. Ոչ,3. Ոչ,Հաշմանդամության թոշակ Նպաստ,4. Միշտ այցելում եմ օգնականի ուղեկցությամբ,"5. Օգնականի ուղեկցությամբ /ծնող, ընկեր, հարազա...",5. Ընդհանրապես իրար չենք հասկանում,1. Այո,"Ոտքերի անոթների հետազոտություն, թոքերի բորբոքմ...",2. Ոչ,2. Ոչ,Ցանկանում եմ որ խուլերի նոր սերունդը լավ տիրապ...,NaN,NaN
2,3,2022-06-04 22:30:47.674,Անահիտ Դալալյան,NaN,Մալինա Խառատյան,2022-06-04 00:00:00,Լոռի,Քաղաք,Վանաձոր,Իգական,52,"1. Ամուսնացած եմ, ունեմ երեխաներ",Ամուսին/Կին,Ամուսին/Կին,Խուլ,Որոշ չափով ունեմ,Ընդհանրապես չունեմ,Որոշ չափով ունեմ,Ընդհանրապես չեմ կարողանում,Ընդհանրապես չունեմ,"Ունեցել եմ խոսքի խնդիր, սակայն չեմ դիմել խոսքա...",Լսողական սարք չեմ կրում,NaN,NaN,Երբեք,Միշտ,Երբեք,Երբեք,Շատ գոհ եմ,NaN,"Ոչ լավ, ոչ վատ",Շատ լավ,Շատ լավ,Բացակայում է,"Ոչ լավ, ոչ վատ",Լավ,Լավ,"Ոչ լավ, ոչ վատ",Բացակայում է,Բացակայում է,4. Վատ,4. Վատ,Ընդհանրապես չեմ տիրապետում,Ընդհանրապես չեմ տիրապետում,NaN,1. Ժեստերի լեզվի թարգմանություն,Ընդհանրապես անհրաժեշտ չէ,Ընդհանրապես անհրաժեշտ չէ,Ընդհանրապես անհրաժեշտ չէ,Ընդհանրապես անհրաժեշտ չէ,Շատ անհրաժեշտ է,"3. Չգիտեմ, թե դա ինչ է",Ընդհանրապես չեմ լսել,Ընդհանրապես չեմ լսել,"Ոչ, չեմ դիմել","Ոչ, չեմ դիմել","Ոչ, չեմ դիմել",NaN,Երբեք,Երբեք,Երբեք,Երբեք,Երբեմն,Երբեմն,Երբեք,Երբեք,Երբեք,Ամբողջովին ինքնուրույն եմ,Հիմնականում ինքնուրույն եմ,Ամբողջովին ինքնուրույն եմ,Հիմնականում ինքնուրույն եմ,Հիմնականում ինքնուրույն եմ,Հիմնական հանրակրթական դպրոց,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1. Այո,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"6. Գործազուրկ, որը չի փնտրում աշխատանք ԱՆՑՈՒՄ D2",Ինձ հարմար աշխատանք չեմ գտնում դրա համար էլ չե...,NaN,2. Ոչ,2. Ոչ ԱՆՑՈՒՄ D7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3. Ընդհանրապես չգիտեմ իմ աշխատանքային իրավունք...,NaN,NaN,NaN,NaN,Կարուձև,2. Ոչ,3. Ոչ,2. Հաշմանդամության թոշակ,4. Միշտ այցելում եմ օգնականի ուղեկցությամբ,"5. Օգնականի ուղեկցությամբ /ծնող, ընկեր, հարազա...",5. Ընդհանրապես իրար չենք հասկանում,1. Այո,Կույր աղիքի վիրահատություն անվճար,2. Ոչ,2. Ոչ,"Բժշկական հաստատություններում, ոստիկանությունու...",NaN,NaN
3,4,2022-06-07 18:43:56.862,Անահիտ Դալալյան,NaN,Աննա Մարգարյան,2022-06-07 00:00:00,Լոռի,Քաղաք,Վանաձոր,Իգական,20,"4. Ամուսնացած չեմ, չունեմ զուգընկեր","Հայր, Մայր, Քույր/Եղբայր",Ոչ մեկը,Թույլ լսող,Ընդհանրապես չունեմ,Ընդհանրապես չունեմ,Ընդհանրապես չունեմ,Որոշ չափով ունեմ,Ընդհանրապես չունեմ,"Ունեցել եմ խոսքի խնդիր, սակայն չեմ դիմել խոսքա...",Լսողական սարք երկկողմանի,Առաջին անգամ Պետական հավաստագրի միջոցով երկրոր...,Շատ գոհ եմ,Երբեմն,Միշտ,Հաճախ,Երբեմն,Շատ գոհ եմ,NaN,Լավ,Շատ լավ,Շատ լավ,"Ոչ լավ, ոչ վատ",Լավ,Շատ լավ,"Ոչ լավ, ոչ վատ",Լավ,Բացակայում է,Բացակայում է,4. Վատ,3. Բավարար,Ընդհանրապես չեմ տիրապետում,Ընդհանրապես չեմ տիրապետում,NaN,1. Ժեստերի լեզվի թարգմանություն,Ընդհանրապես անհրաժեշտ չէ,Ընդհանրապես անհրաժեշտ չէ,Ընդհանրապես անհրաժեշտ չէ,Ընդհանրապես անհրաժեշտ չէ,Շատ անհրաժեշտ է,"3. Չգիտեմ, թե դա ինչ է",Ընդհանրապես չեմ լսել,Ընդհանրապես չեմ լսել,"Ոչ, չեմ դիմել","Ոչ, չեմ դիմել","Ոչ, չեմ դիմել",NaN,Միշտ,Երբեմն,Երբեք,Երբեմն,Երբեք,Միշտ,Երբեք,Երբեք,Երբեմն,Հիմնականում ինքնուրույն եմ,Հիմնականում ինքնուրույն եմ,Հիմնականում ինքնուրույն եմ,Հիմնականում ինքնուրույն եմ,Հիմնականում ինքնուրույն եմ,Ավագ հանրակրթական դպրոց,2009 - 2021,2. Հիմնականում մատչելի է,3. Հաղորդակցվում ենք որոշ դժվարություններով,"3. Այո, երբեմն",Երբեք չեմ առնչվել,Երբեք չեմ առնչվել,Երբեք չեմ առնչվել,2. Հիմնականում դրական,2. Քիչ թե շատ ընկերական,1. Այո,3. Ավելի շուտ բացասական,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"5. Գործազուրկ, որը փնտրում է աշխատանք ԱՆՑՈՒՄ D3",NaN,1. Ծանոթների միջոցով,2. Ոչ,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3. Ընդհանրապես չգիտեմ իմ աշխատանքային իրավունք...,NaN,NaN,NaN,NaN,Լուսանկարչուհի և նկարչուհի,2. Ոչ,3. Ոչ,2. Հաշմանդամության թոշակ,3. Հիմնականում այցելում եմ օգնականի ուղեկցությամբ,"5. Օգնականի ուղեկցությամբ /ծնող, ընկեր, հարազա...",5. Ընդհանրապես իրար չենք հասկանում,2. Ոչ ԱՆՑՈՒՄ D6,NaN,2. Ոչ,2. Ոչ,NaN,2. Հիմնականում պատրաստակամ են,NaN

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 145 entries, 0 to 144
Columns: 132 entries, Unnamed: 0 to Հարցազրույցը իրականացվել է՝.1
dtypes: datetime64[us](1), float64(1), int64(1), object(8), str(121)
memory usage: 149.7+ KB

In [5]:

df.describe()

       Unnamed: 0                   Timestamp  Unnamed: 96
count  145.000000                         145          0.0
mean    73.000000  2022-08-17 23:31:35.962227          NaN
min      1.000000  2022-05-24 07:45:52.711000          NaN
25%     37.000000  2022-06-06 15:47:44.386000          NaN
50%     73.000000  2022-09-30 16:45:42.408000          NaN
75%    109.000000  2022-10-06 15:56:16.533000          NaN
max    145.000000  2022-10-12 16:24:10.927000          NaN
std     42.001984                         NaN          NaN

In [6]:
list(df.columns)

['Unnamed: 0',
 'Timestamp',
 'Հարցազրուցավարի անուն ազգանուն',
 'Հարցազրույցը իրականացվել է՝',
 'Հարցվողի անուն ազգանուն',
 'Հարցազրույցի ամսաթիվ',
 'A1. Նշե՛ք Ձեր մարզը:',
 'A2. Նշեք Ձեր բնակավայրի տիպը:',
 'A3. Նշեք Ձեր բնակավայրի/վարչական շրջանի անունը:',
 'A4. Հարցվողի սեռը:',
 'A5. Նշե՛ք, խնդրեմ, Ձեր տարիքը:',
 'A6. Նշե՛ք Ձեր ամուսնական կարգավիճակը',
 'A7. Ու՞մ հետ եք բնակվում: ',
 'A8. Ձեզ հետ բնակվող ընտանիքի անդամներից ովքե՞ր ունեն լսողության խնդիրներ: ',
 'A9. Դուք Ձեզ համարում եք՝',
 'A10. Առողջության բաղադրիչների վերաբերյալ դժվարություններ ունե՞ք: [Տեսողություն]',
 'A10. Առողջության բաղադրիչների վերաբերյալ դժվարություններ ունե՞ք: [Հենաշարժողական վիճակ /քայլել, վազել/]',
 'A10. Առողջության բաղադրիչների վերաբերյալ դժվարություններ ունե՞ք: [Հիշողություն և կենտրոնացում]',
 'A10. Առողջության բաղադրիչների վերաբերյալ դժվարություններ ունե՞ք: [Խոսելու կարողություն]',
 'A10. Առողջության բաղադրիչների վերաբերյալ դժվարություններ ունե՞ք: [Ինքնախնամքի՝ ինքնուրույն հագնվելիս կամ լվացվելիս/լոգանք ընդունելիս դժվարություններ/Ինքնուրույն հագնվելիս կամ լվացվելիս/լոգանք ընդունելիս]',
 'A11. Նշված տարբերակներից, ո՞րն է առավել լավ բնութագրում Ձեր իրավիճակը:',
 'A13. Հետևյալ աջակցող միջոցներից որո՞նք եք կրում:',
 'A14. Ու՞մ միջոցով եք ձեռք բերել Ձեր աջակցող միջոցը /իմպլանտը կամ սարքը/:',
 'A15. Որքանո՞վ եք գոհ Ձեր աջակցող միջոցից կամ սարքից:',
 'A16. Որքան հաճախ եք կիրառում հաղորդակցության հետևյալ ձևերից յուրաքանչյուրը:   [Շուրթերից կարդալը]',
 'A16. Որքան հաճախ եք կիրառում հաղորդակցության հետևյալ ձևերից յուրաքանչյուրը:   [Ժեստերով հաղորդկացվելը]',
 'A16. Որքան հաճախ եք կիրառում հաղորդակցության հետևյալ ձևերից յուրաքանչյուրը:   [Բանավոր շփումը ինքնուրույն]',
 'A16. Որքան հաճախ եք կիրառում հաղորդակցության հետևյալ ձևերից յուրաքանչյուրը:   [Գրավոր շփումը]',
 'A17. ԱՐՑՆԵԼ ՄԻԱՅՆ ԵԹԵ ՆԱԽՈՐԴ ՀԱՐՑՈՒՄ ՆՇԵԼ Է, ՈՐ ՀԱՂՈՐԴԱԿՑՎՈՒՄ Է ԺԵՍՏԵՐԻ ԼԵԶՎՈՎ  Ընդհանուր առմամբ, որքանո՞վ եք գոհ ժեստերի լեզվի թարգմանիչների աշխատանքից: ',
 'Որքանով եք գոհ Ձեր անցած խոսքային թերապիայից: ',
 'B1. Հետևյալ կարողություններից և հմտություններից որոնց եք տիրապետում և ինչ չափով:  [Մարդկանց հետ հաղորդակցվելու հմտություններ]',
 'B1. Հետևյալ կարողություններից և հմտություններից որոնց եք տիրապետում և ինչ չափով:  [Սնունդ պատրաստելու հմտություններ]',
 'B1. Հետևյալ կարողություններից և հմտություններից որոնց եք տիրապետում և ինչ չափով:  [Հիգիենային հետևելու հմտություններ]',
 'B1. Հետևյալ կարողություններից և հմտություններից որոնց եք տիրապետում և ինչ չափով:  [Մեքենա վարելու հմտություններ]',
 'B1. Հետևյալ կարողություններից և հմտություններից որոնց եք տիրապետում և ինչ չափով:  [Ժամանակի կառավարման հմտություններ]',
 'B1. Հետևյալ կարողություններից և հմտություններից որոնց եք տիրապետում և ինչ չափով:  [Ձեր առօրյան պլանավորելու հմտություններ]',
 'B1. Հետևյալ կարողություններից և հմտություններից որոնց եք տիրապետում և ինչ չափով:  [Նպատակադրման հմտություններ]',
 'B1. Հետևյալ կարողություններից և հմտություններից որոնց եք տիրապետում և ինչ չափով:  [Ձեր ծախսերը պլանավորելու հմտություններ]',
 'B1. Հետևյալ կարողություններից և հմտություններից որոնց եք տիրապետում և ինչ չափով:  [Բանկային համակարգից օգտվելու հմտություններ]',
 'B1. Հետևյալ կարողություններից և հմտություններից որոնց եք տիրապետում և ինչ չափով:  [Օնլայն վճարումներ կատարելու հտություններ]',
 'B2. Ինչպես կգնահատեք գրելու Ձեր կարողությունը: ',
 'B3. Ինչպես կգնահատեք կարդալու Ձեր կարողությունը: ',
 'B4. Որքանո՞վ եք տիրապետում հետևյալ օտար լեզուներից յուրաքանչյուրին. [Ռուսերեն]',
 'B4. Որքանո՞վ եք տիրապետում հետևյալ օտար լեզուներից յուրաքանչյուրին. [Անգլերեն]',
 'B4. Որքանո՞վ եք տիրապետում հետևյալ օտար լեզուներից յուրաքանչյուրին. [Այլ]',
 'B5. Նշված տարբերակներից որը կլիներ հեռուստատեսային հաղորդումները մատչելի դարձնելու Ձեզ ամենահարմար տարբերակը',
 'B6. Ստորև թվարկված հարմարեցումներից որոնց կարիքը ունեք:\t [Սղագրողների առկայություն]',
 'B6. Ստորև թվարկված հարմարեցումներից որոնց կարիքը ունեք:\t [Աջակցող լսողական սարք]',
 'B6. Ստորև թվարկված հարմարեցումներից որոնց կարիքը ունեք:\t [Տեքստային հաղորդակցում]',
 'B6. Ստորև թվարկված հարմարեցումներից որոնց կարիքը ունեք:\t [Լուսագրերով տեսանյութեր]',
 'B6. Ստորև թվարկված հարմարեցումներից որոնց կարիքը ունեք:\t [ՀԺԼ թարգմանություն]',
 'B7. Ունե՞ք ինքնակենսագրական (CV (սիվի) կամ  ռեզյումե):',
 'B8. Ասացե՛ք խնդրեմ, ստորև թվարկվածներից E5. Ասացե՛ք խնդրեմ, որքանո՞վ եք ծանոք ստորև թվարկված իրավական կարգավորումներին: [Հաշմանդամություն ունեցող անձանց իրավունքների մասին ՄԱԿ-ի կոնվենցիա]',
 'B8. Ասացե՛ք խնդրեմ, ստորև թվարկվածներից E5. Ասացե՛ք խնդրեմ, որքանո՞վ եք ծանոք ստորև թվարկված իրավական կարգավորումներին: [Հաշմանդամություն ունեցող անձանց իրավունքների մասին օրենք, ընդունված 2021 թվականին]',
 'B9. Ձեր իրավունքների ոտնահարման դեպքում, նշված տարբերակներից որի՞ն եք երբևէ դիմել: [Մարդու իրավունքների պաշտպանի գրասենյակ]',
 'B9. Ձեր իրավունքների ոտնահարման դեպքում, նշված տարբերակներից որի՞ն եք երբևէ դիմել: [Որևէ Հասարակական կազմակերպություն]',
 'B9. Ձեր իրավունքների ոտնահարման դեպքում, նշված տարբերակներից որի՞ն եք երբևէ դիմել: [Իրավաբանի]',
 'B9. Ձեր իրավունքների ոտնահարման դեպքում, նշված տարբերակներից որի՞ն եք երբևէ դիմել: [Այլ]',
 'B10. Ինչ հաճախականությամբ եք կատարում հետևյալ գործողություններից յուրաքանչյուրը: [Տանը կամ այգում մարմնամարզություն կատարել]',
 'B10. Ինչ հաճախականությամբ եք կատարում հետևյալ գործողություններից յուրաքանչյուրը: [Սպորտային խմբակ հաճախել]',
 'B10. Ինչ հաճախականությամբ եք կատարում հետևյալ գործողություններից յուրաքանչյուրը: [Մարզասրահ հաճախել]',
 'B10. Ինչ հաճախականությամբ եք կատարում հետևյալ գործողություններից յուրաքանչյուրը: [Թատրոն գնալ]',
 'B10. Ինչ հաճախականությամբ եք կատարում հետևյալ գործողություններից յուրաքանչյուրը: [Կինո գնալ]',
 'B10. Ինչ հաճախականությամբ եք կատարում հետևյալ գործողություններից յուրաքանչյուրը: [Տանը կինո նայել]',
 'B10. Ինչ հաճախականությամբ եք կատարում հետևյալ գործողություններից յուրաքանչյուրը: [Մասնակցել Ձեր համայնքի ավագանու նիստերին]',
 'B10. Ինչ հաճախականությամբ եք կատարում հետևյալ գործողություններից յուրաքանչյուրը: [Մասնակցել համայնքային քննարկումներին]',
 'B10. Ինչ հաճախականությամբ եք կատարում հետևյալ գործողություններից յուրաքանչյուրը: [Մասնակցել համայնքային շաբաթօրյակների]',
 'B11. Ո՞րքանով եք ինքնուրույն կայացնում Ձեր կյանքի հետևյալ ոլորտների վերաբերյալ որոշումները: [Աշխատելու վերաբերյալ որոշումները]',
 'B11. Ո՞րքանով եք ինքնուրույն կայացնում Ձեր կյանքի հետևյալ ոլորտների վերաբերյալ որոշումները: [Անձնական կյանքի վերաբերյալ որոշումները]',
 'B11. Ո՞րքանով եք ինքնուրույն կայացնում Ձեր կյանքի հետևյալ ոլորտների վերաբերյալ որոշումները: [Ընկերների վերաբերյալ որոշումները]',
 'B11. Ո՞րքանով եք ինքնուրույն կայացնում Ձեր կյանքի հետևյալ ոլորտների վերաբերյալ որոշումները: [Ֆինանսական ծախսերի վերաբերալ որոշումները]',
 'B11. Ո՞րքանով եք ինքնուրույն կայացնում Ձեր կյանքի հետևյալ ոլորտների վերաբերյալ որոշումները: [Ժամանցի վերաբերյալ որոշումները]',
 'C1. Ո՞րն է Ձեր կրթական աստիճանը:',
 'C1. որ թվականներին եք սովորել դպրոցում:',
 'C2. Որքանո՞վ  է  դպրոցում դասավանդող ուսուցիչների  բանավոր խոսքը Ձեզ համար մատչելի:',
 'C4. Ինչպե՞ս կգնահատեք ուսուցիչների հետ Ձեր հաղորդակցությունը:',
 'C5. Արդյոք ունե՞ք ընտրության հնարավորություն, հանձնարարությունը ներկայացնել Ձեզ համար մատչելի եղանակով:',
 'C6. Ինչպե՞ս կգնահատեք դպրոցի հետևյալ մասնագետների աշխատանքի արդյունավետությունը: [Հատուկ մանկավարժ]',
 'C6. Ինչպե՞ս կգնահատեք դպրոցի հետևյալ մասնագետների աշխատանքի արդյունավետությունը: [Սոցիալական աշխատող]',
 'C6. Ինչպե՞ս կգնահատեք դպրոցի հետևյալ մասնագետների աշխատանքի արդյունավետությունը: [Հոգեբան]',
 'C7. Ընդհանուր առմամբ, ինչպիսի՞ն է տվյալ ուսումնական հաստատության ուսուցիչների  վերաբերմունքը Ձեր հանդեպ. ',
 'C8. Հետևյալ տարբերակներից ո՞րն է առավել լավ բնութագրում Ձեր՝ Ձեր համադասարանցիների հետ ունեցած հարաբերությունները. ',
 'C9. Կուզեի՞ք որ դպրոցում աշակերտները սովորեին ժեստերի լեզու:',
 'C10. ՀԱՐՑՆԵԼ ՄԻԱՅՆ ԱՅՆ ԴԵՊՔՈՒՄ, ԵԹԵ ԴՊՐՈՑԱԿԱՆ ԿՐԹՈՒԹՅՈՒՆԸ ՀԱՄԸՆԿԵԼ Է ՔՈՎԻԴԻ ԺԱՄԱՆԱԿԱՀԱՏՎԱԾԻ ՀԵՏ:  Ինչպե՞ս է ազդել COVID-19 համավարակի ժամանակ հեռավար կրթության անցնելը Ձեր սովորելու արդյունավետության վրա:',
 'C11. Ասացե՛ք, խնդրեմ, թե որ թվականներին եք սովորել տվյալ ուսումնական հաստատությունում:',
 'C12. Որքանո՞վ է տվյալ ուսումնական հաստատությունում դասավանդող դասախոսների  բանավոր խոսքը Ձեզ համար մատչելի:',
 'C13. Արդյո՞ք դասախոսը դասը պատմելիս, կամ որպես օժանդակ նյութ Ձեզ տրամադրում է ուսումնական տեսանյութեր:',
 'C14. Արդյո՞ք ուսուցիչների կողմից տրամադրված տեսանյութերը լուսագրերով են:',
 'C15. Ընդհանուր առմամբ, որքանո՞վ են տվյալ ուսումնական հաստատությունում դասավանդող դասախոսները պատրաստակամ անհատական մոտեցում ցուցաբերել սովորողին:',
 'C16. Ինչպե՞ս կգնահատեք տվյալ ուսումնական հաստատությունում դասավանդող դասախոսների հետ Ձեր հաղորդակցությունը:',
 'C17. Արդյոք ունե՞ք ընտրության հնարավորություն, քննությունը հանձնել Ձեզ համար մատչելի եղանակով /գրավոր քննություն կամ բանավոր քննություն/:',
 'C18. Ինչպե՞ս կգնահատեք դեկանատի աշխատակիցների հետ հաղորդակցվելու արդյունավետությունը:',
 'C19.  Որքանո՞վ է տվյալ ուսումնական հաստատության տարածքը հարմար, լսողության խնդիրներ ունեցող անձանց համար վիզուալ կողմնորոշվելու տեսանկյունից (ցուցանակների առկայություն, համարակալումներ և այլն)',
 'C20. Ընդհանուր առմամբ, ինչպիսի՞ն է տվյալ ուսումնական հաստատության դասախոսների վերաբերմունքը Ձեր հանդեպ.',
 'C21. Հետևյալ տարբերակներից ո՞րն է առավել լավ բնութագրում Ձեր կուրսեցիների հետ ունեցած հարաբերությունները.',
 'C22. ՀԱՐՑՆԵԼ ՄԻԱՅՆ ԱՅՆ ԴԵՊՔՈՒՄ, ԵԹԵ ՆԱԽՆԱԿԱՆ, ՄԻՋԻՆ ՄԱՍՆԱԳԻՏԱԿԱՆ ԵՎ ԲԱՐՁՐԱԳՈՒՅՆ ԿՐԹՈՒԹՅՈՒՆԸ ՀԱՄԸՆԿԵԼ Է ՔՈՎԻԴԻ ԺԱՄԱՆԱԿԱՀԱՏՎԱԾԻ ՀԵՏ:                                              Ինչպե՞ս է ազդել COVID-19 համավարակի ժամանակ հեռավար կրթության անցնելը Ձեր սովորելու արդյունավետության վրա:',
 'Unnamed: 96',
 'D1. Նշեք Ձեր հիմնական զբաղվածությունը.',
 'D2. Որո՞նք են աշխատանք չփնտրելու պատճառները:',
 'D3. Ինչպե՞ս եք փորձում գտնել աշխատանք (Կարող եք նշել 1-ից ավելի տարբերակ):',
 'D4. Տեղյա՞կ եք արդյոք միասնական սոցիալական ծառայության (նախկինում՝ զբաղվածության պետական գործակալություն) մասին:',
 'D5. Երբևէ դիմե՞լ եք միասնական սոցիալական ծառայություն (նախկինում զբաղվածության գործակալություն) աշխատանք գտնելու հարցով:',
 'D6. Հաջողվե՞լ է միասնական սոցիալական ծառայությանը (նախկինում զբաղվածության գործակալություն) Ձեզ համար աշխատանք գտնել:',
 'D7. Ձեր աշխատանքը՝',
 'D8. Նշե՛ք այն աշխատանքը, որը Դուք ներկա պահին կատարում եք',
 'D9. Արդյո՞ք Ձեր ներկայիս աշխատանքը համապատասխանում է Ձեր մասնագիտական կրթությանը:',
 'D10. Ինչպե՞ս եք գտել Ձեր ներկայիս աշխատանքը: ',
 'D11. Որքա՞ն ժամանակ է որ կատարում եք Ձեր աշխատանքը ',
 'D12. Ձեր աշխատանքային գրաֆիկը՝ ',
 'D13. Օրական միջինում քանի՞ ժամ եք աշխատում ՝ ',
 'D14. Ամսվա մեջ միջինում քանի՞ օր եք աշխատում՝  ',
 'D15. Ինչպե՞ս կգնահատեք գործատուի հետ Ձեր հաղորդակցության արդյունավետությունը: ',
 'D16. Ինչպե՞ս կգնահատեք Ձեր գործընկերների/մյուս աշխատակիցների հետ Ձեր հաղորդակցության արդյունավետությունը: ',
 'D17. Գիտե՞ք արդյոք Ձեր աշխատանքային իրավունքների մասին:',
 'D18. Ըստ Ձեզ, որքանո՞վ են Ձեր աշխատանքային իրավունքները պաշտպանված Ձեր աշխատավայրում:',
 'D19. Ունե՞ք արդյոք աշխատանքային պայմանագիր:',
 'D20. Ինչպիսի՞ն է գործատուի վերաբերմունքը Ձեր հանդեպ:',
 'D21. Ինչպիսի՞ն է Ձեր գործընկերների/մյուս աշխատակիցների վերաբերմունքը Ձեր հանդեպ.',
 'D22. Ո՞րն է Ձեր երազանքի աշխատանքը ',
 'D23. Արդյոք դուք կամ Ձեր ընտանիքի անդամներից մեկը կորցրե՞լ է իր աշխատանքը COVID-19 համավարակի հետևանքով:',
 'D24. Արդյո՞ք Դուք կամ Ձեր ընտանիքի անդամներից մեկը առողջական խնդիրներ է ձեռք բերել/վիրավորվել կամ զոհվել է  44 օրյա պատերազմի հետևանքով:',
 'D25. Ինչպիսի՞ սոցիալական ապահովություն եք ստանում: ',
 'E1. Որքանո՞վ եք ինքնուրույն այցելում առողջապահական հաստատություններ, Ձեզ անհրաժեշտ բժշկական ծառայություններից օգտվելու համար:',
 'E2. Սովորաբար, ինչպե՞ս եք հաղորդակցվում բժիշկների հետ:',
 'E3. Ասացե՛ք, խնդրեմ, ընդհանուր առմամբ, որքանով է Ձեր և բժիկների միջև հաղորդակցությունը արդյունավետ:',
 'E4. Օգտվել կամ օգտվու՞մ եք արդյոք որևէ բժշկական ծառայությունից անվճար:',
 'E5. Ո՞ր ծառայությունից/ծառայություններից եք անվճար օգտվում:',
 'E6. Երբևէ դիմե՞լ եք հոգեբանի:',
 'E7. Ունե՞ք արդյոք հոգեբանի ծառայության կարիք:',
 'Նշումների համար',
 'C3. Ընդհանուր առմամբ, որքանո"վ են ուսուցիչները պատրաստակամ անհատական մոտեցում ցուցաբերել աշակերտին:',
 'Հարցազրույցը իրականացվել է՝.1']

In [7]:
df.isnull().sum()

Unnamed: 0                                                                                               0
Timestamp                                                                                                0
Հարցազրուցավարի անուն ազգանուն                                                                           0
Հարցազրույցը իրականացվել է՝                                                                             38
Հարցվողի անուն ազգանուն                                                                                  0
                                                                                                      ...
E6. Երբևէ դիմե՞լ եք հոգեբանի:                                                                            0
E7. Ունե՞ք արդյոք հոգեբանի ծառայության կարիք:                                                            0
Նշումների համար                                                                                         84
C3. Ընդհանուր առմամբ, որքանո"վ են ուսուցիչները պատրաստակամ անհատական մոտեցում ցուցաբերել աշակերտին:    136
Հարցազրույցը իրականացվել է՝.1                                                                           44
Length: 132, dtype: int64

In [8]:
df.columns.tolist()

['Unnamed: 0',
 'Timestamp',
 'Հարցազրուցավարի անուն ազգանուն',
 'Հարցազրույցը իրականացվել է՝',
 'Հարցվողի անուն ազգանուն',
 'Հարցազրույցի ամսաթիվ',
 'A1. Նշե՛ք Ձեր մարզը:',
 'A2. Նշեք Ձեր բնակավայրի տիպը:',
 'A3. Նշեք Ձեր բնակավայրի/վարչական շրջանի անունը:',
 'A4. Հարցվողի սեռը:',
 'A5. Նշե՛ք, խնդրեմ, Ձեր տարիքը:',
 'A6. Նշե՛ք Ձեր ամուսնական կարգավիճակը',
 'A7. Ու՞մ հետ եք բնակվում: ',
 'A8. Ձեզ հետ բնակվող ընտանիքի անդամներից ովքե՞ր ունեն լսողության խնդիրներ: ',
 'A9. Դուք Ձեզ համարում եք՝',
 'A10. Առողջության բաղադրիչների վերաբերյալ դժվարություններ ունե՞ք: [Տեսողություն]',
 'A10. Առողջության բաղադրիչների վերաբերյալ դժվարություններ ունե՞ք: [Հենաշարժողական վիճակ /քայլել, վազել/]',
 'A10. Առողջության բաղադրիչների վերաբերյալ դժվարություններ ունե՞ք: [Հիշողություն և կենտրոնացում]',
 'A10. Առողջության բաղադրիչների վերաբերյալ դժվարություններ ունե՞ք: [Խոսելու կարողություն]',
 'A10. Առողջության բաղադրիչների վերաբերյալ դժվարություններ ունե՞ք: [Ինքնախնամքի՝ ինքնուրույն հագնվելիս կամ լվացվելիս/լոգանք ընդունելիս դժվարություններ/Ինքնուրույն հագնվելիս կամ լվացվելիս/լոգանք ընդունելիս]',
 'A11. Նշված տարբերակներից, ո՞րն է առավել լավ բնութագրում Ձեր իրավիճակը:',
 'A13. Հետևյալ աջակցող միջոցներից որո՞նք եք կրում:',
 'A14. Ու՞մ միջոցով եք ձեռք բերել Ձեր աջակցող միջոցը /իմպլանտը կամ սարքը/:',
 'A15. Որքանո՞վ եք գոհ Ձեր աջակցող միջոցից կամ սարքից:',
 'A16. Որքան հաճախ եք կիրառում հաղորդակցության հետևյալ ձևերից յուրաքանչյուրը:   [Շուրթերից կարդալը]',
 'A16. Որքան հաճախ եք կիրառում հաղորդակցության հետևյալ ձևերից յուրաքանչյուրը:   [Ժեստերով հաղորդկացվելը]',
 'A16. Որքան հաճախ եք կիրառում հաղորդակցության հետևյալ ձևերից յուրաքանչյուրը:   [Բանավոր շփումը ինքնուրույն]',
 'A16. Որքան հաճախ եք կիրառում հաղորդակցության հետևյալ ձևերից յուրաքանչյուրը:   [Գրավոր շփումը]',
 'A17. ԱՐՑՆԵԼ ՄԻԱՅՆ ԵԹԵ ՆԱԽՈՐԴ ՀԱՐՑՈՒՄ ՆՇԵԼ Է, ՈՐ ՀԱՂՈՐԴԱԿՑՎՈՒՄ Է ԺԵՍՏԵՐԻ ԼԵԶՎՈՎ  Ընդհանուր առմամբ, որքանո՞վ եք գոհ ժեստերի լեզվի թարգմանիչների աշխատանքից: ',
 'Որքանով եք գոհ Ձեր անցած խոսքային թերապիայից: ',
 'B1. Հետևյալ կարողություններից և հմտություններից որոնց եք տիրապետում և ինչ չափով:  [Մարդկանց հետ հաղորդակցվելու հմտություններ]',
 'B1. Հետևյալ կարողություններից և հմտություններից որոնց եք տիրապետում և ինչ չափով:  [Սնունդ պատրաստելու հմտություններ]',
 'B1. Հետևյալ կարողություններից և հմտություններից որոնց եք տիրապետում և ինչ չափով:  [Հիգիենային հետևելու հմտություններ]',
 'B1. Հետևյալ կարողություններից և հմտություններից որոնց եք տիրապետում և ինչ չափով:  [Մեքենա վարելու հմտություններ]',
 'B1. Հետևյալ կարողություններից և հմտություններից որոնց եք տիրապետում և ինչ չափով:  [Ժամանակի կառավարման հմտություններ]',
 'B1. Հետևյալ կարողություններից և հմտություններից որոնց եք տիրապետում և ինչ չափով:  [Ձեր առօրյան պլանավորելու հմտություններ]',
 'B1. Հետևյալ կարողություններից և հմտություններից որոնց եք տիրապետում և ինչ չափով:  [Նպատակադրման հմտություններ]',
 'B1. Հետևյալ կարողություններից և հմտություններից որոնց եք տիրապետում և ինչ չափով:  [Ձեր ծախսերը պլանավորելու հմտություններ]',
 'B1. Հետևյալ կարողություններից և հմտություններից որոնց եք տիրապետում և ինչ չափով:  [Բանկային համակարգից օգտվելու հմտություններ]',
 'B1. Հետևյալ կարողություններից և հմտություններից որոնց եք տիրապետում և ինչ չափով:  [Օնլայն վճարումներ կատարելու հտություններ]',
 'B2. Ինչպես կգնահատեք գրելու Ձեր կարողությունը: ',
 'B3. Ինչպես կգնահատեք կարդալու Ձեր կարողությունը: ',
 'B4. Որքանո՞վ եք տիրապետում հետևյալ օտար լեզուներից յուրաքանչյուրին. [Ռուսերեն]',
 'B4. Որքանո՞վ եք տիրապետում հետևյալ օտար լեզուներից յուրաքանչյուրին. [Անգլերեն]',
 'B4. Որքանո՞վ եք տիրապետում հետևյալ օտար լեզուներից յուրաքանչյուրին. [Այլ]',
 'B5. Նշված տարբերակներից որը կլիներ հեռուստատեսային հաղորդումները մատչելի դարձնելու Ձեզ ամենահարմար տարբերակը',
 'B6. Ստորև թվարկված հարմարեցումներից որոնց կարիքը ունեք:\t [Սղագրողների առկայություն]',
 'B6. Ստորև թվարկված հարմարեցումներից որոնց կարիքը ունեք:\t [Աջակցող լսողական սարք]',
 'B6. Ստորև թվարկված հարմարեցումներից որոնց կարիքը ունեք:\t [Տեքստային հաղորդակցում]',
 'B6. Ստորև թվարկված հարմարեցումներից որոնց կարիքը ունեք:\t [Լուսագրերով տեսանյութեր]',
 'B6. Ստորև թվարկված հարմարեցումներից որոնց կարիքը ունեք:\t [ՀԺԼ թարգմանություն]',
 'B7. Ունե՞ք ինքնակենսագրական (CV (սիվի) կամ  ռեզյումե):',
 'B8. Ասացե՛ք խնդրեմ, ստորև թվարկվածներից E5. Ասացե՛ք խնդրեմ, որքանո՞վ եք ծանոք ստորև թվարկված իրավական կարգավորումներին: [Հաշմանդամություն ունեցող անձանց իրավունքների մասին ՄԱԿ-ի կոնվենցիա]',
 'B8. Ասացե՛ք խնդրեմ, ստորև թվարկվածներից E5. Ասացե՛ք խնդրեմ, որքանո՞վ եք ծանոք ստորև թվարկված իրավական կարգավորումներին: [Հաշմանդամություն ունեցող անձանց իրավունքների մասին օրենք, ընդունված 2021 թվականին]',
 'B9. Ձեր իրավունքների ոտնահարման դեպքում, նշված տարբերակներից որի՞ն եք երբևէ դիմել: [Մարդու իրավունքների պաշտպանի գրասենյակ]',
 'B9. Ձեր իրավունքների ոտնահարման դեպքում, նշված տարբերակներից որի՞ն եք երբևէ դիմել: [Որևէ Հասարակական կազմակերպություն]',
 'B9. Ձեր իրավունքների ոտնահարման դեպքում, նշված տարբերակներից որի՞ն եք երբևէ դիմել: [Իրավաբանի]',
 'B9. Ձեր իրավունքների ոտնահարման դեպքում, նշված տարբերակներից որի՞ն եք երբևէ դիմել: [Այլ]',
 'B10. Ինչ հաճախականությամբ եք կատարում հետևյալ գործողություններից յուրաքանչյուրը: [Տանը կամ այգում մարմնամարզություն կատարել]',
 'B10. Ինչ հաճախականությամբ եք կատարում հետևյալ գործողություններից յուրաքանչյուրը: [Սպորտային խմբակ հաճախել]',
 'B10. Ինչ հաճախականությամբ եք կատարում հետևյալ գործողություններից յուրաքանչյուրը: [Մարզասրահ հաճախել]',
 'B10. Ինչ հաճախականությամբ եք կատարում հետևյալ գործողություններից յուրաքանչյուրը: [Թատրոն գնալ]',
 'B10. Ինչ հաճախականությամբ եք կատարում հետևյալ գործողություններից յուրաքանչյուրը: [Կինո գնալ]',
 'B10. Ինչ հաճախականությամբ եք կատարում հետևյալ գործողություններից յուրաքանչյուրը: [Տանը կինո նայել]',
 'B10. Ինչ հաճախականությամբ եք կատարում հետևյալ գործողություններից յուրաքանչյուրը: [Մասնակցել Ձեր համայնքի ավագանու նիստերին]',
 'B10. Ինչ հաճախականությամբ եք կատարում հետևյալ գործողություններից յուրաքանչյուրը: [Մասնակցել համայնքային քննարկումներին]',
 'B10. Ինչ հաճախականությամբ եք կատարում հետևյալ գործողություններից յուրաքանչյուրը: [Մասնակցել համայնքային շաբաթօրյակների]',
 'B11. Ո՞րքանով եք ինքնուրույն կայացնում Ձեր կյանքի հետևյալ ոլորտների վերաբերյալ որոշումները: [Աշխատելու վերաբերյալ որոշումները]',
 'B11. Ո՞րքանով եք ինքնուրույն կայացնում Ձեր կյանքի հետևյալ ոլորտների վերաբերյալ որոշումները: [Անձնական կյանքի վերաբերյալ որոշումները]',
 'B11. Ո՞րքանով եք ինքնուրույն կայացնում Ձեր կյանքի հետևյալ ոլորտների վերաբերյալ որոշումները: [Ընկերների վերաբերյալ որոշումները]',
 'B11. Ո՞րքանով եք ինքնուրույն կայացնում Ձեր կյանքի հետևյալ ոլորտների վերաբերյալ որոշումները: [Ֆինանսական ծախսերի վերաբերալ որոշումները]',
 'B11. Ո՞րքանով եք ինքնուրույն կայացնում Ձեր կյանքի հետևյալ ոլորտների վերաբերյալ որոշումները: [Ժամանցի վերաբերյալ որոշումները]',
 'C1. Ո՞րն է Ձեր կրթական աստիճանը:',
 'C1. որ թվականներին եք սովորել դպրոցում:',
 'C2. Որքանո՞վ  է  դպրոցում դասավանդող ուսուցիչների  բանավոր խոսքը Ձեզ համար մատչելի:',
 'C4. Ինչպե՞ս կգնահատեք ուսուցիչների հետ Ձեր հաղորդակցությունը:',
 'C5. Արդյոք ունե՞ք ընտրության հնարավորություն, հանձնարարությունը ներկայացնել Ձեզ համար մատչելի եղանակով:',
 'C6. Ինչպե՞ս կգնահատեք դպրոցի հետևյալ մասնագետների աշխատանքի արդյունավետությունը: [Հատուկ մանկավարժ]',
 'C6. Ինչպե՞ս կգնահատեք դպրոցի հետևյալ մասնագետների աշխատանքի արդյունավետությունը: [Սոցիալական աշխատող]',
 'C6. Ինչպե՞ս կգնահատեք դպրոցի հետևյալ մասնագետների աշխատանքի արդյունավետությունը: [Հոգեբան]',
 'C7. Ընդհանուր առմամբ, ինչպիսի՞ն է տվյալ ուսումնական հաստատության ուսուցիչների  վերաբերմունքը Ձեր հանդեպ. ',
 'C8. Հետևյալ տարբերակներից ո՞րն է առավել լավ բնութագրում Ձեր՝ Ձեր համադասարանցիների հետ ունեցած հարաբերությունները. ',
 'C9. Կուզեի՞ք որ դպրոցում աշակերտները սովորեին ժեստերի լեզու:',
 'C10. ՀԱՐՑՆԵԼ ՄԻԱՅՆ ԱՅՆ ԴԵՊՔՈՒՄ, ԵԹԵ ԴՊՐՈՑԱԿԱՆ ԿՐԹՈՒԹՅՈՒՆԸ ՀԱՄԸՆԿԵԼ Է ՔՈՎԻԴԻ ԺԱՄԱՆԱԿԱՀԱՏՎԱԾԻ ՀԵՏ:  Ինչպե՞ս է ազդել COVID-19 համավարակի ժամանակ հեռավար կրթության անցնելը Ձեր սովորելու արդյունավետության վրա:',
 'C11. Ասացե՛ք, խնդրեմ, թե որ թվականներին եք սովորել տվյալ ուսումնական հաստատությունում:',
 'C12. Որքանո՞վ է տվյալ ուսումնական հաստատությունում դասավանդող դասախոսների  բանավոր խոսքը Ձեզ համար մատչելի:',
 'C13. Արդյո՞ք դասախոսը դասը պատմելիս, կամ որպես օժանդակ նյութ Ձեզ տրամադրում է ուսումնական տեսանյութեր:',
 'C14. Արդյո՞ք ուսուցիչների կողմից տրամադրված տեսանյութերը լուսագրերով են:',
 'C15. Ընդհանուր առմամբ, որքանո՞վ են տվյալ ուսումնական հաստատությունում դասավանդող դասախոսները պատրաստակամ անհատական մոտեցում ցուցաբերել սովորողին:',
 'C16. Ինչպե՞ս կգնահատեք տվյալ ուսումնական հաստատությունում դասավանդող դասախոսների հետ Ձեր հաղորդակցությունը:',
 'C17. Արդյոք ունե՞ք ընտրության հնարավորություն, քննությունը հանձնել Ձեզ համար մատչելի եղանակով /գրավոր քննություն կամ բանավոր քննություն/:',
 'C18. Ինչպե՞ս կգնահատեք դեկանատի աշխատակիցների հետ հաղորդակցվելու արդյունավետությունը:',
 'C19.  Որքանո՞վ է տվյալ ուսումնական հաստատության տարածքը հարմար, լսողության խնդիրներ ունեցող անձանց համար վիզուալ կողմնորոշվելու տեսանկյունից (ցուցանակների առկայություն, համարակալումներ և այլն)',
 'C20. Ընդհանուր առմամբ, ինչպիսի՞ն է տվյալ ուսումնական հաստատության դասախոսների վերաբերմունքը Ձեր հանդեպ.',
 'C21. Հետևյալ տարբերակներից ո՞րն է առավել լավ բնութագրում Ձեր կուրսեցիների հետ ունեցած հարաբերությունները.',
 'C22. ՀԱՐՑՆԵԼ ՄԻԱՅՆ ԱՅՆ ԴԵՊՔՈՒՄ, ԵԹԵ ՆԱԽՆԱԿԱՆ, ՄԻՋԻՆ ՄԱՍՆԱԳԻՏԱԿԱՆ ԵՎ ԲԱՐՁՐԱԳՈՒՅՆ ԿՐԹՈՒԹՅՈՒՆԸ ՀԱՄԸՆԿԵԼ Է ՔՈՎԻԴԻ ԺԱՄԱՆԱԿԱՀԱՏՎԱԾԻ ՀԵՏ:                                              Ինչպե՞ս է ազդել COVID-19 համավարակի ժամանակ հեռավար կրթության անցնելը Ձեր սովորելու արդյունավետության վրա:',
 'Unnamed: 96',
 'D1. Նշեք Ձեր հիմնական զբաղվածությունը.',
 'D2. Որո՞նք են աշխատանք չփնտրելու պատճառները:',
 'D3. Ինչպե՞ս եք փորձում գտնել աշխատանք (Կարող եք նշել 1-ից ավելի տարբերակ):',
 'D4. Տեղյա՞կ եք արդյոք միասնական սոցիալական ծառայության (նախկինում՝ զբաղվածության պետական գործակալություն) մասին:',
 'D5. Երբևէ դիմե՞լ եք միասնական սոցիալական ծառայություն (նախկինում զբաղվածության գործակալություն) աշխատանք գտնելու հարցով:',
 'D6. Հաջողվե՞լ է միասնական սոցիալական ծառայությանը (նախկինում զբաղվածության գործակալություն) Ձեզ համար աշխատանք գտնել:',
 'D7. Ձեր աշխատանքը՝',
 'D8. Նշե՛ք այն աշխատանքը, որը Դուք ներկա պահին կատարում եք',
 'D9. Արդյո՞ք Ձեր ներկայիս աշխատանքը համապատասխանում է Ձեր մասնագիտական կրթությանը:',
 'D10. Ինչպե՞ս եք գտել Ձեր ներկայիս աշխատանքը: ',
 'D11. Որքա՞ն ժամանակ է որ կատարում եք Ձեր աշխատանքը ',
 'D12. Ձեր աշխատանքային գրաֆիկը՝ ',
 'D13. Օրական միջինում քանի՞ ժամ եք աշխատում ՝ ',
 'D14. Ամսվա մեջ միջինում քանի՞ օր եք աշխատում՝  ',
 'D15. Ինչպե՞ս կգնահատեք գործատուի հետ Ձեր հաղորդակցության արդյունավետությունը: ',
 'D16. Ինչպե՞ս կգնահատեք Ձեր գործընկերների/մյուս աշխատակիցների հետ Ձեր հաղորդակցության արդյունավետությունը: ',
 'D17. Գիտե՞ք արդյոք Ձեր աշխատանքային իրավունքների մասին:',
 'D18. Ըստ Ձեզ, որքանո՞վ են Ձեր աշխատանքային իրավունքները պաշտպանված Ձեր աշխատավայրում:',
 'D19. Ունե՞ք արդյոք աշխատանքային պայմանագիր:',
 'D20. Ինչպիսի՞ն է գործատուի վերաբերմունքը Ձեր հանդեպ:',
 'D21. Ինչպիսի՞ն է Ձեր գործընկերների/մյուս աշխատակիցների վերաբերմունքը Ձեր հանդեպ.',
 'D22. Ո՞րն է Ձեր երազանքի աշխատանքը ',
 'D23. Արդյոք դուք կամ Ձեր ընտանիքի անդամներից մեկը կորցրե՞լ է իր աշխատանքը COVID-19 համավարակի հետևանքով:',
 'D24. Արդյո՞ք Դուք կամ Ձեր ընտանիքի անդամներից մեկը առողջական խնդիրներ է ձեռք բերել/վիրավորվել կամ զոհվել է  44 օրյա պատերազմի հետևանքով:',
 'D25. Ինչպիսի՞ սոցիալական ապահովություն եք ստանում: ',
 'E1. Որքանո՞վ եք ինքնուրույն այցելում առողջապահական հաստատություններ, Ձեզ անհրաժեշտ բժշկական ծառայություններից օգտվելու համար:',
 'E2. Սովորաբար, ինչպե՞ս եք հաղորդակցվում բժիշկների հետ:',
 'E3. Ասացե՛ք, խնդրեմ, ընդհանուր առմամբ, որքանով է Ձեր և բժիկների միջև հաղորդակցությունը արդյունավետ:',
 'E4. Օգտվել կամ օգտվու՞մ եք արդյոք որևէ բժշկական ծառայությունից անվճար:',
 'E5. Ո՞ր ծառայությունից/ծառայություններից եք անվճար օգտվում:',
 'E6. Երբևէ դիմե՞լ եք հոգեբանի:',
 'E7. Ունե՞ք արդյոք հոգեբանի ծառայության կարիք:',
 'Նշումների համար',
 'C3. Ընդհանուր առմամբ, որքանո"վ են ուսուցիչները պատրաստակամ անհատական մոտեցում ցուցաբերել աշակերտին:',
 'Հարցազրույցը իրականացվել է՝.1']

In [10]:
# df['new'] = df['']

In [11]:
df.head()

,Unnamed: 0,Timestamp,Հարցազրուցավարի անուն ազգանուն,Հարցազրույցը իրականացվել է՝,Հարցվողի անուն ազգանուն,Հարցազրույցի ամսաթիվ,A1. Նշե՛ք Ձեր մարզը:,A2. Նշեք Ձեր բնակավայրի տիպը:,A3. Նշեք Ձեր բնակավայրի/վարչական շրջանի անունը:,A4. Հարցվողի սեռը:,"A5. Նշե՛ք, խնդրեմ, Ձեր տարիքը:",A6. Նշե՛ք Ձեր ամուսնական կարգավիճակը,A7. Ու՞մ հետ եք բնակվում:,A8. Ձեզ հետ բնակվող ընտանիքի անդամներից ովքե՞ր ունեն լսողության խնդիրներ:,A9. Դուք Ձեզ համարում եք՝,A10. Առողջության բաղադրիչների վերաբերյալ դժվարություններ ունե՞ք: [Տեսողություն],"A10. Առողջության բաղադրիչների վերաբերյալ դժվարություններ ունե՞ք: [Հենաշարժողական վիճակ /քայլել, վազել/]",A10. Առողջության բաղադրիչների վերաբերյալ դժվարություններ ունե՞ք: [Հիշողություն և կենտրոնացում],A10. Առողջության բաղադրիչների վերաբերյալ դժվարություններ ունե՞ք: [Խոսելու կարողություն],A10. Առողջության բաղադրիչների վերաբերյալ դժվարություններ ունե՞ք: [Ինքնախնամքի՝ ինքնուրույն հագնվելիս կամ լվացվելիս/լոգանք ընդունելիս դժվարություններ/Ինքնուրույն հագնվելիս կամ լվացվելիս/լոգանք ընդունելիս],"A11. Նշված տարբերակներից, ո՞րն է առավել լավ բնութագրում Ձեր իրավիճակը:",A13. Հետևյալ աջակցող միջոցներից որո՞նք եք կրում:,A14. Ու՞մ միջոցով եք ձեռք բերել Ձեր աջակցող միջոցը /իմպլանտը կամ սարքը/:,A15. Որքանո՞վ եք գոհ Ձեր աջակցող միջոցից կամ սարքից:,A16. Որքան հաճախ եք կիրառում հաղորդակցության հետևյալ ձևերից յուրաքանչյուրը: [Շուրթերից կարդալը],A16. Որքան հաճախ եք կիրառում հաղորդակցության հետևյալ ձևերից յուրաքանչյուրը: [Ժեստերով հաղորդկացվելը],A16. Որքան հաճախ եք կիրառում հաղորդակցության հետևյալ ձևերից յուրաքանչյուրը: [Բանավոր շփումը ինքնուրույն],A16. Որքան հաճախ եք կիրառում հաղորդակցության հետևյալ ձևերից յուրաքանչյուրը: [Գրավոր շփումը],"A17. ԱՐՑՆԵԼ ՄԻԱՅՆ ԵԹԵ ՆԱԽՈՐԴ ՀԱՐՑՈՒՄ ՆՇԵԼ Է, ՈՐ ՀԱՂՈՐԴԱԿՑՎՈՒՄ Է ԺԵՍՏԵՐԻ ԼԵԶՎՈՎ Ընդհանուր առմամբ, որքանո՞վ եք գոհ ժեստերի լեզվի թարգմանիչների աշխատանքից:",Որքանով եք գոհ Ձեր անցած խոսքային թերապիայից:,B1. Հետևյալ կարողություններից և հմտություններից որոնց եք տիրապետում և ինչ չափով: [Մարդկանց հետ հաղորդակցվելու հմտություններ],B1. Հետևյալ կարողություններից և հմտություններից որոնց եք տիրապետում և ինչ չափով: [Սնունդ պատրաստելու հմտություններ],B1. Հետևյալ կարողություններից և հմտություններից որոնց եք տիրապետում և ինչ չափով: [Հիգիենային հետևելու հմտություններ],B1. Հետևյալ կարողություններից և հմտություններից որոնց եք տիրապետում և ինչ չափով: [Մեքենա վարելու հմտություններ],B1. Հետևյալ կարողություններից և հմտություններից որոնց եք տիրապետում և ինչ չափով: [Ժամանակի կառավարման հմտություններ],B1. Հետևյալ կարողություններից և հմտություններից որոնց եք տիրապետում և ինչ չափով: [Ձեր առօրյան պլանավորելու հմտություններ],B1. Հետևյալ կարողություններից և հմտություններից որոնց եք տիրապետում և ինչ չափով: [Նպատակադրման հմտություններ],B1. Հետևյալ կարողություններից և հմտություններից որոնց եք տիրապետում և ինչ չափով: [Ձեր ծախսերը պլանավորելու հմտություններ],B1. Հետևյալ կարողություններից և հմտություններից որոնց եք տիրապետում և ինչ չափով: [Բանկային համակարգից օգտվելու հմտություններ],B1. Հետևյալ կարողություններից և հմտություններից որոնց եք տիրապետում և ինչ չափով: [Օնլայն վճարումներ կատարելու հտություններ],B2. Ինչպես կգնահատեք գրելու Ձեր կարողությունը:,B3. Ինչպես կգնահատեք կարդալու Ձեր կարողությունը:,B4. Որքանո՞վ եք տիրապետում հետևյալ օտար լեզուներից յուրաքանչյուրին. [Ռուսերեն],B4. Որքանո՞վ եք տիրապետում հետևյալ օտար լեզուներից յուրաքանչյուրին. [Անգլերեն],B4. Որքանո՞վ եք տիրապետում հետևյալ օտար լեզուներից յուրաքանչյուրին. [Այլ],B5. Նշված տարբերակներից որը կլիներ հեռուստատեսային հաղորդումները մատչելի դարձնելու Ձեզ ամենահարմար տարբերակը,B6. Ստորև թվարկված հարմարեցումներից որոնց կարիքը ունեք:\t [Սղագրողների առկայություն],B6. Ստորև թվարկված հարմարեցումներից որոնց կարիքը ունեք:\t [Աջակցող լսողական սարք],B6. Ստորև թվարկված հարմարեցումներից որոնց կարիքը ունեք:\t [Տեքստային հաղորդակցում],B6. Ստորև թվարկված հարմարեցումներից որոնց կարիքը ունեք:\t [Լուսագրերով տեսանյութեր],B6. Ստորև թվարկված հարմարեցումներից որոնց կարիքը ունեք:\t [ՀԺԼ թարգմանություն],B7. Ունե՞ք ինքնակենսագրական (CV (սիվի) կամ ռեզյումե):,"B8. Ասացե՛ք խնդրեմ, ստորև թվարկվածներից E5. Ասացե՛ք խնդրեմ, որքանո՞վ եք ծանոք ստորև թվարկված իրավական կարգավորումներին: [Հաշմանդամություն ունեցող անձանց իրավունքների մասին ՄԱԿ-ի կոնվենցիա]","B8. Ասացե՛ք խնդրեմ, ստորև թվարկվածներից E5. Ասացե՛ք խնդրեմ, որքանո՞վ եք ծանոք ստորև թվարկված իրավական կարգավորումներին: [Հաշմանդամություն ունեցող անձանց իրավունքների մասին օրենք, ընդունված 2021 թվականին]","B9. Ձեր իրավունքների ոտնահարման դեպքում, նշված տարբերակներից որի՞ն եք երբևէ դիմել: [Մարդու իրավունքների պաշտպանի գրասենյակ]","B9. Ձեր իրավունքների ոտնահարման դեպքում, նշված տարբերակներից որի՞ն եք երբևէ դիմել: [Որևէ Հասարակական կազմակերպություն]","B9. Ձեր իրավունքների ոտնահարման դեպքում, նշված տարբերակներից որի՞ն եք երբևէ դիմել: [Իրավաբանի]","B9. Ձեր իրավունքների ոտնահարման դեպքում, նշված տարբերակներից որի՞ն եք երբևէ դիմել: [Այլ]",B10. Ինչ հաճախականությամբ եք կատարում հետևյալ գործողություններից յուրաքանչյուրը: [Տանը կամ այգում մարմնամարզություն կատարել],B10. Ինչ հաճախականությամբ եք կատարում հետևյալ գործողություններից յուրաքանչյուրը: [Սպորտային խմբակ հաճախել],B10. Ինչ հաճախականությամբ եք կատարում հետևյալ գործողություններից յուրաքանչյուրը: [Մարզասրահ հաճախել],B10. Ինչ հաճախականությամբ եք կատարում հետևյալ գործողություններից յուրաքանչյուրը: [Թատրոն գնալ],B10. Ինչ հաճախականությամբ եք կատարում հետևյալ գործողություններից յուրաքանչյուրը: [Կինո գնալ],B10. Ինչ հաճախականությամբ եք կատարում հետևյալ գործողություններից յուրաքանչյուրը: [Տանը կինո նայել],B10. Ինչ հաճախականությամբ եք կատարում հետևյալ գործողություններից յուրաքանչյուրը: [Մասնակցել Ձեր համայնքի ավագանու նիստերին],B10. Ինչ հաճախականությամբ եք կատարում հետևյալ գործողություններից յուրաքանչյուրը: [Մասնակցել համայնքային քննարկումներին],B10. Ինչ հաճախականությամբ եք կատարում հետևյալ գործողություններից յուրաքանչյուրը: [Մասնակցել համայնքային շաբաթօրյակների],B11. Ո՞րքանով եք ինքնուրույն կայացնում Ձեր կյանքի հետևյալ ոլորտների վերաբերյալ որոշումները: [Աշխատելու վերաբերյալ որոշումները],B11. Ո՞րքանով եք ինքնուրույն կայացնում Ձեր կյանքի հետևյալ ոլորտների վերաբերյալ որոշումները: [Անձնական կյանքի վերաբերյալ որոշումները],B11. Ո՞րքանով եք ինքնուրույն կայացնում Ձեր կյանքի հետևյալ ոլորտների վերաբերյալ որոշումները: [Ընկերների վերաբերյալ որոշումները],B11. Ո՞րքանով եք ինքնուրույն կայացնում Ձեր կյանքի հետևյալ ոլորտների վերաբերյալ որոշումները: [Ֆինանսական ծախսերի վերաբերալ որոշումները],B11. Ո՞րքանով եք ինքնուրույն կայացնում Ձեր կյանքի հետևյալ ոլորտների վերաբերյալ որոշումները: [Ժամանցի վերաբերյալ որոշումները],C1. Ո՞րն է Ձեր կրթական աստիճանը:,C1. որ թվականներին եք սովորել դպրոցում:,C2. Որքանո՞վ է դպրոցում դասավանդող ուսուցիչների բանավոր խոսքը Ձեզ համար մատչելի:,C4. Ինչպե՞ս կգնահատեք ուսուցիչների հետ Ձեր հաղորդակցությունը:,"C5. Արդյոք ունե՞ք ընտրության հնարավորություն, հանձնարարությունը ներկայացնել Ձեզ համար մատչելի եղանակով:",C6. Ինչպե՞ս կգնահատեք դպրոցի հետևյալ մասնագետների աշխատանքի արդյունավետությունը: [Հատուկ մանկավարժ],C6. Ինչպե՞ս կգնահատեք դպրոցի հետևյալ մասնագետների աշխատանքի արդյունավետությունը: [Սոցիալական աշխատող],C6. Ինչպե՞ս կգնահատեք դպրոցի հետևյալ մասնագետների աշխատանքի արդյունավետությունը: [Հոգեբան],"C7. Ընդհանուր առմամբ, ինչպիսի՞ն է տվյալ ուսումնական հաստատության ուսուցիչների վերաբերմունքը Ձեր հանդեպ.",C8. Հետևյալ տարբերակներից ո՞րն է առավել լավ բնութագրում Ձեր՝ Ձեր համադասարանցիների հետ ունեցած հարաբերությունները.,C9. Կուզեի՞ք որ դպրոցում աշակերտները սովորեին ժեստերի լեզու:,"C10. ՀԱՐՑՆԵԼ ՄԻԱՅՆ ԱՅՆ ԴԵՊՔՈՒՄ, ԵԹԵ ԴՊՐՈՑԱԿԱՆ ԿՐԹՈՒԹՅՈՒՆԸ ՀԱՄԸՆԿԵԼ Է ՔՈՎԻԴԻ ԺԱՄԱՆԱԿԱՀԱՏՎԱԾԻ ՀԵՏ: Ինչպե՞ս է ազդել COVID-19 համավարակի ժամանակ հեռավար կրթության անցնելը Ձեր սովորելու արդյունավետության վրա:","C11. Ասացե՛ք, խնդրեմ, թե որ թվականներին եք սովորել տվյալ ուսումնական հաստատությունում:",C12. Որքանո՞վ է տվյալ ուսումնական հաստատությունում դասավանդող դասախոսների բանավոր խոսքը Ձեզ համար մատչելի:,"C13. Արդյո՞ք դասախոսը դասը պատմելիս, կամ որպես օժանդակ նյութ Ձեզ տրամադրում է ուսումնական տեսանյութեր:",C14. Արդյո՞ք ուսուցիչների կողմից տրամադրված տեսանյութերը լուսագրերով են:,"C15. Ընդհանուր առմամբ, որքանո՞վ են տվյալ ուսումնական հաստատությունում դասավանդող դասախոսները պատրաստակամ անհատական մոտեցում ցուցաբերել սովորողին:",C16. Ինչպե՞ս կգնահատեք տվյալ ուսումնական հաստատությունում դասավանդող դասախոսների հետ Ձեր հաղորդակցությունը:,"C17. Արդյոք ունե՞ք ընտրության հնարավորություն, քննությունը հանձնել Ձեզ համար մատչելի եղանակով /գրավոր քննություն կամ բանավոր քննություն/:",C18. Ինչպե՞ս կգնահատեք դեկանատի աշխատակիցների հետ հաղորդակցվելու արդյունավետությունը:,"C19. Որքանո՞վ է տվյալ ուսումնական հաստատության տարածքը հարմար, լսողության խնդիրներ ունեցող անձանց համար վիզուալ կողմնորոշվելու տեսանկյունից (ցուցանակների առկայություն, համարակալումներ և այլն)","C20. Ընդհանուր առմամբ, ինչպիսի՞ն է տվյալ ուսումնական հաստատության դասախոսների վերաբերմունքը Ձեր հանդեպ.",C21. Հետևյալ տարբերակներից ո՞րն է առավել լավ բնութագրում Ձեր կուրսեցիների հետ ունեցած հարաբերությունները.,"C22. ՀԱՐՑՆԵԼ ՄԻԱՅՆ ԱՅՆ ԴԵՊՔՈՒՄ, ԵԹԵ ՆԱԽՆԱԿԱՆ, ՄԻՋԻՆ ՄԱՍՆԱԳԻՏԱԿԱՆ ԵՎ ԲԱՐՁՐԱԳՈՒՅՆ ԿՐԹՈՒԹՅՈՒՆԸ ՀԱՄԸՆԿԵԼ Է ՔՈՎԻԴԻ ԺԱՄԱՆԱԿԱՀԱՏՎԱԾԻ ՀԵՏ: Ինչպե՞ս է ազդել COVID-19 համավարակի ժամանակ հեռավար կրթության անցնելը Ձեր սովորելու արդյունավետության վրա:",Unnamed: 96,D1. Նշեք Ձեր հիմնական զբաղվածությունը.,D2. Որո՞նք են աշխատանք չփնտրելու պատճառները:,D3. Ինչպե՞ս եք փորձում գտնել աշխատանք (Կարող եք նշել 1-ից ավելի տարբերակ):,D4. Տեղյա՞կ եք արդյոք միասնական սոցիալական ծառայության (նախկինում՝ զբաղվածության պետական գործակալություն) մասին:,D5. Երբևէ դիմե՞լ եք միասնական սոցիալական ծառայություն (նախկինում զբաղվածության գործակալություն) աշխատանք գտնելու հարցով:,D6. Հաջողվե՞լ է միասնական սոցիալական ծառայությանը (նախկինում զբաղվածության գործակալություն) Ձեզ համար աշխատանք գտնել:,D7. Ձեր աշխատանքը՝,"D8. Նշե՛ք այն աշխատանքը, որը Դուք ներկա պահին կատարում եք",D9. Արդյո՞ք Ձեր ներկայիս աշխատանքը համապատասխանում է Ձեր մասնագիտական կրթությանը:,D10. Ինչպե՞ս եք գտել Ձեր ներկայիս աշխատանքը:,D11. Որքա՞ն ժամանակ է որ կատարում եք Ձեր աշխատանքը,D12. Ձեր աշխատանքային գրաֆիկը՝,D13. Օրական միջինում քանի՞ ժամ եք աշխատում ՝,D14. Ամսվա մեջ միջինում քանի՞ օր եք աշխատում՝,D15. Ինչպե՞ս կգնահատեք գործատուի հետ Ձեր հաղորդակցության արդյունավետությունը:,D16. Ինչպե՞ս կգնահատեք Ձեր գործընկերների/մյուս աշխատակիցների հետ Ձեր հաղորդակցության արդյունավետությունը:,D17. Գիտե՞ք արդյոք Ձեր աշխատանքային իրավունքների մասին:,"D18. Ըստ Ձեզ, որքանո՞վ են Ձեր աշխատանքային իրավունքները պաշտպանված Ձեր աշխատավայրում:",D19. Ունե՞ք արդյոք աշխատանքային պայմանագիր:,D20. Ինչպիսի՞ն է գործատուի վերաբերմունքը Ձեր հանդեպ:,D21. Ինչպիսի՞ն է Ձեր գործընկերների/մյուս աշխատակիցների վերաբերմունքը Ձեր հանդեպ.,D22. Ո՞րն է Ձեր երազանքի աշխատանքը,D23. Արդյոք դուք կամ Ձեր ընտանիքի անդամներից մեկը կորցրե՞լ է իր աշխատանքը COVID-19 համավարակի հետևանքով:,D24. Արդյո՞ք Դուք կամ Ձեր ընտանիքի անդամներից մեկը առողջական խնդիրներ է ձեռք բերել/վիրավորվել կամ զոհվել է 44 օրյա պատերազմի հետևանքով:,D25. Ինչպիսի՞ սոցիալական ապահովություն եք ստանում:,"E1. Որքանո՞վ եք ինքնուրույն այցելում առողջապահական հաստատություններ, Ձեզ անհրաժեշտ բժշկական ծառայություններից օգտվելու համար:","E2. Սովորաբար, ինչպե՞ս եք հաղորդակցվում բժիշկների հետ:","E3. Ասացե՛ք, խնդրեմ, ընդհանուր առմամբ, որքանով է Ձեր և բժիկների միջև հաղորդակցությունը արդյունավետ:",E4. Օգտվել կամ օգտվու՞մ եք արդյոք որևէ բժշկական ծառայությունից անվճար:,E5. Ո՞ր ծառայությունից/ծառայություններից եք անվճար օգտվում:,E6. Երբևէ դիմե՞լ եք հոգեբանի:,E7. Ունե՞ք արդյոք հոգեբանի ծառայության կարիք:,Նշումների համար,"C3. Ընդհանուր առմամբ, որքանո""վ են ուսուցիչները պատրաստակամ անհատական մոտեցում ցուցաբերել աշակերտին:",Հարցազրույցը իրականացվել է՝.1
0,1,2022-05-29 19:05:36.394,Անահիտ Դալալյան,NaN,Անգելինա Քառյան,2022-05-29 00:00:00,Լոռի,Քաղաք,Վանաձոր,Իգական,23,"4. Ամուսնացած չեմ, չունեմ զուգընկեր",Մայր,Ոչ մեկը,Խուլ,Ընդհանրապես չունեմ,Ընդհանրապես չունեմ,Ընդհանրապես չունեմ,Շատ դժվարություններ ունեմ,Ընդհանրապես չունեմ,Ունեցել եմ խոսքի խնդիր և դիմել եմ խոսքային թեր...,Լսողական սարք երկկողմանի կրել է մինչև 17 տարեկ...,"Չգիտեմ, մայրս է զբաղվել այդ հարցով:","Այն ժամանակ կրելուց դժգոհ եմ եղել հարմար չէր, ...",Հաճախ,Միշտ,Հաճախ,Հաճախ,Շատ գոհ եմ,Շատ գոհ եմ,Շատ լավ,"Ոչ լավ, ոչ վատ",Շատ լավ,"Ոչ լավ, ոչ վատ","Ոչ լավ, ոչ վատ",Լավ,"Ոչ լավ, ոչ վատ",Լավ,"Ոչ լավ, ոչ վատ",Վատ,3. Բավարար,3. Բավարար,Ավելի շուտ չեմ տիրապետում,Ավելի շուտ չեմ տիրապետում,NaN,1. Ժեստերի լեզվի թարգմանություն,Ընդհանրապես անհրաժեշտ չէ,Ավելի շուտ անհրաժեշտ չէ,Ավելի շուտ անհրաժեշտ է,Ավելի շուտ անհրաժեշտ չէ,Շատ անհրաժեշտ է,"3. Չգիտեմ, թե դա ինչ է",Ընդհանրապես չեմ լսել,Որոշ չափով տեղյակ եմ,"Ոչ, չեմ դիմել","Ոչ, չեմ դիմել","Ոչ, չեմ դիմել",NaN,Միշտ,Պարբերաբար,Պարբերաբար,Երբեմն,Երբեք,Երբեք,Երբեք,Երբեք,Երբեմն,Հիմնականում ինքնուրույն եմ,Հիմնականում ինքնուրույն եմ,Հիմնականում ինքնուրույն եմ,Հիմնականում ինքնուրույն եմ,Հիմնականում ինքնուրույն չեմ,Մասնավոր ուսումնական կենտրոն,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"5. Գործազուրկ, որը փնտրում է աշխատանք ԱՆՑՈՒՄ D3",NaN,1. Ծանոթների միջոցով,2. Ոչ,2. Ոչ ԱՆՑՈՒՄ D7,NaN,Այս պահին չեմ աշխատում,Այս պահին չեմ աշխատում,Այս պահին չեմ աշխատում,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"2. Այո, որոշ չափով գիտեմ իմ աշխատանքային իրավո...",NaN,NaN,NaN,NaN,Մատնահարդար լինելը,2. Ոչ,3. Ոչ,2. Հաշմանդամության թոշակ,3. Հիմնականում այցելում եմ օգնականի ուղեկցությամբ,"Օգնականի ուղեկցությամբ, իսկ մենակով գնալու դեպ...",2. Հաղորդակցվում ենք հիմնականում առանց դժվարու...,3. Դժվարանում եմ պատասխանել,NaN,2. Ոչ,2. Ոչ,NaN,NaN,NaN
1,2,2022-05-30 22:16:40.892,Անահիտ Դալալյան,NaN,Անահիտ Ղաբուզյան,2022-05-30 00:00:00,Լոռի,Քաղաք,Վանաձոր,Իգական,51,"1. Ամուսնացած եմ, չունեմ երեխաներ",Ամուսին/Կին,Ամուսին/Կին,Խուլ,Որոշ չափով ունեմ,Ընդհանրապես չունեմ,Որոշ չափով ունեմ,Ընդհանրապես չեմ կարողանում,Ընդհանրապես չունեմ,"Ունեցել եմ խոսքի խնդիր, սակայն չեմ դիմել խոսքա...",Լսողական սարք չեմ կրում,NaN,NaN,Երբեմն,Միշտ,Երբեմն,Երբեմն,Շատ գոհ եմ,NaN,"Ոչ լավ, ոչ վատ",Շատ լավ,Շատ լավ,Բացակայում է,Լավ,Լավ,"Ոչ լավ, ոչ վատ",Լավ,Լավ,Բացակայում է,3. Բավարար,3. Բավարար,Ավելի շուտ չեմ տիրապետում,Ընդհանրապես չեմ տիրապետում,NaN,1. Ժեստերի լեզվի թարգմանություն,Ընդհանրապես անհրաժեշտ չէ,Ընդհանրապես անհրաժեշտ չէ,Ընդհանրապես անհրաժեշտ չէ,Ընդհանրապես անհրաժեշտ չէ,Շատ անհրաժեշտ է,"3. Չգիտեմ, թե դա ինչ է",Ընդհանրապես չեմ լսել,Ընդհանրապես չեմ լսել,"Ոչ, չեմ դիմել","Ոչ, չեմ դիմել","Ոչ, չեմ դիմել",NaN,Երբեք,Երբեք,Երբեք,Երբեք,Երբեմն,Միշտ,Երբեք,Երբեք,Երբեք,Ամբողջովին ինքնուրույն եմ,Ամբողջովին ինքնուրույն եմ,Ամբողջովին ինքնուրույն եմ,Հիմնականում ինքնուրույն չեմ,Ամբողջովին ինքնուրույն եմ,Հիմնական հանրակրթական դպրոց,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"5. Գործազուրկ, որը փնտրում է աշխատանք ԱՆՑՈՒՄ D3",NaN,1. Ծանոթների միջոցով,2. Ոչ,NaN,NaN,NaN,NaN,4. Մասնագիտական կրթություն չունեմ,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"2. Այո, որոշ չափով գիտեմ իմ աշխատանքային իրավո...",NaN,NaN,NaN,NaN,Մաքրություն անել եմ սիրում:,2. Ոչ,3. Ոչ,Հաշմանդամության թոշակ Նպաստ,4. Միշտ այցելում եմ օգնականի ուղեկցությամբ,"5. Օգնականի ուղեկցությամբ /ծնող, ընկեր, հարազա...",5. Ընդհանրապես իրար չենք հասկանում,1. Այո,"Ոտքերի անոթների հետազոտություն, թոքերի բորբոքմ...",2. Ոչ,2. Ոչ,Ցանկանում եմ որ խուլերի նոր սերունդը լավ տիրապ...,NaN,NaN
2,3,2022-06-04 22:30:47.674,Անահիտ Դալալյան,NaN,Մալինա Խառատյան,2022-06-04 00:00:00,Լոռի,Քաղաք,Վանաձոր,Իգական,52,"1. Ամուսնացած եմ, ունեմ երեխաներ",Ամուսին/Կին,Ամուսին/Կին,Խուլ,Որոշ չափով ունեմ,Ընդհանրապես չունեմ,Որոշ չափով ունեմ,Ընդհանրապես չեմ կարողանում,Ընդհանրապես չունեմ,"Ունեցել եմ խոսքի խնդիր, սակայն չեմ դիմել խոսքա...",Լսողական սարք չեմ կրում,NaN,NaN,Երբեք,Միշտ,Երբեք,Երբեք,Շատ գոհ եմ,NaN,"Ոչ լավ, ոչ վատ",Շատ լավ,Շատ լավ,Բացակայում է,"Ոչ լավ, ոչ վատ",Լավ,Լավ,"Ոչ լավ, ոչ վատ",Բացակայում է,Բացակայում է,4. Վատ,4. Վատ,Ընդհանրապես չեմ տիրապետում,Ընդհանրապես չեմ տիրապետում,NaN,1. Ժեստերի լեզվի թարգմանություն,Ընդհանրապես անհրաժեշտ չէ,Ընդհանրապես անհրաժեշտ չէ,Ընդհանրապես անհրաժեշտ չէ,Ընդհանրապես անհրաժեշտ չէ,Շատ անհրաժեշտ է,"3. Չգիտեմ, թե դա ինչ է",Ընդհանրապես չեմ լսել,Ընդհանրապես չեմ լսել,"Ոչ, չեմ դիմել","Ոչ, չեմ դիմել","Ոչ, չեմ դիմել",NaN,Երբեք,Երբեք,Երբեք,Երբեք,Երբեմն,Երբեմն,Երբեք,Երբեք,Երբեք,Ամբողջովին ինքնուրույն եմ,Հիմնականում ինքնուրույն եմ,Ամբողջովին ինքնուրույն եմ,Հիմնականում ինքնուրույն եմ,Հիմնականում ինքնուրույն եմ,Հիմնական հանրակրթական դպրոց,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1. Այո,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"6. Գործազուրկ, որը չի փնտրում աշխատանք ԱՆՑՈՒՄ D2",Ինձ հարմար աշխատանք չեմ գտնում դրա համար էլ չե...,NaN,2. Ոչ,2. Ոչ ԱՆՑՈՒՄ D7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3. Ընդհանրապես չգիտեմ իմ աշխատանքային իրավունք...,NaN,NaN,NaN,NaN,Կարուձև,2. Ոչ,3. Ոչ,2. Հաշմանդամության թոշակ,4. Միշտ այցելում եմ օգնականի ուղեկցությամբ,"5. Օգնականի ուղեկցությամբ /ծնող, ընկեր, հարազա...",5. Ընդհանրապես իրար չենք հասկանում,1. Այո,Կույր աղիքի վիրահատություն անվճար,2. Ոչ,2. Ոչ,"Բժշկական հաստատություններում, ոստիկանությունու...",NaN,NaN
3,4,2022-06-07 18:43:56.862,Անահիտ Դալալյան,NaN,Աննա Մարգարյան,2022-06-07 00:00:00,Լոռի,Քաղաք,Վանաձոր,Իգական,20,"4. Ամուսնացած չեմ, չունեմ զուգընկեր","Հայր, Մայր, Քույր/Եղբայր",Ոչ մեկը,Թույլ լսող,Ընդհանրապես չունեմ,Ընդհանրապես չունեմ,Ընդհանրապես չունեմ,Որոշ չափով ունեմ,Ընդհանրապես չունեմ,"Ունեցել եմ խոսքի խնդիր, սակայն չեմ դիմել խոսքա...",Լսողական սարք երկկողմանի,Առաջին անգամ Պետական հավաստագրի միջոցով երկրոր...,Շատ գոհ եմ,Երբեմն,Միշտ,Հաճախ,Երբեմն,Շատ գոհ եմ,NaN,Լավ,Շատ լավ,Շատ լավ,"Ոչ լավ, ոչ վատ",Լավ,Շատ լավ,"Ոչ լավ, ոչ վատ",Լավ,Բացակայում է,Բացակայում է,4. Վատ,3. Բավարար,Ընդհանրապես չեմ տիրապետում,Ընդհանրապես չեմ տիրապետում,NaN,1. Ժեստերի լեզվի թարգմանություն,Ընդհանրապես անհրաժեշտ չէ,Ընդհանրապես անհրաժեշտ չէ,Ընդհանրապես անհրաժեշտ չէ,Ընդհանրապես անհրաժեշտ չէ,Շատ անհրաժեշտ է,"3. Չգիտեմ, թե դա ինչ է",Ընդհանրապես չեմ լսել,Ընդհանրապես չեմ լսել,"Ոչ, չեմ դիմել","Ոչ, չեմ դիմել","Ոչ, չեմ դիմել",NaN,Միշտ,Երբեմն,Երբեք,Երբեմն,Երբեք,Միշտ,Երբեք,Երբեք,Երբեմն,Հիմնականում ինքնուրույն եմ,Հիմնականում ինքնուրույն եմ,Հիմնականում ինքնուրույն եմ,Հիմնականում ինքնուրույն եմ,Հիմնականում ինքնուրույն եմ,Ավագ հանրակրթական դպրոց,2009 - 2021,2. Հիմնականում մատչելի է,3. Հաղորդակցվում ենք որոշ դժվարություններով,"3. Այո, երբեմն",Երբեք չեմ առնչվել,Երբեք չեմ առնչվել,Երբեք չեմ առնչվել,2. Հիմնականում դրական,2. Քիչ թե շատ ընկերական,1. Այո,3. Ավելի շուտ բացասական,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"5. Գործազուրկ, որը փնտրում է աշխատանք ԱՆՑՈՒՄ D3",NaN,1. Ծանոթների միջոցով,2. Ոչ,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3. Ընդհանրապես չգիտեմ իմ աշխատանքային իրավունք...,NaN,NaN,NaN,NaN,Լուսանկարչուհի և նկարչուհի,2. Ոչ,3. Ոչ,2. Հաշմանդամության թոշակ,3. Հիմնականում այցելում եմ օգնականի ուղեկցությամբ,"5. Օգնականի ուղեկցությամբ /ծնող, ընկեր, հարազա...",5. Ընդհանրապես իրար չենք հասկանում,2. Ոչ ԱՆՑՈՒՄ D6,NaN,2. Ոչ,2. Ոչ,NaN,2. Հիմնականում պատրաստակամ են,NaN

In [12]:
# Show all columns
pd.set_option("display.max_columns", None)

## 1. կրճատի նորմալ անուններ գրի սյուների անունները
## 2. պահի նրանք որոնք որ պետք են
## 3. դու էստեղ պետքա միաովորես պատասխանը` բաժանելով երկու մասի, լավ /վատ

## Example



df_selected = df[
    ["ID", "Gender", "Sign_Language", "Reading"]
]

df_selected = df_selected.rename(
    columns={
        "Sign_Language": "language_type",
        "Reading": "reading_score"
    }
)

In [20]:
df_selected = df[
    ["Unnamed: 0", "B2. Ինչպես կգնահատեք գրելու Ձեր կարողությունը: ", "B3. Ինչպես կգնահատեք կարդալու Ձեր կարողությունը: " ]
]

In [21]:
df_selected

,Unnamed: 0,B2. Ինչպես կգնահատեք գրելու Ձեր կարողությունը:,B3. Ինչպես կգնահատեք կարդալու Ձեր կարողությունը:
0,1,3. Բավարար,3. Բավարար
1,2,3. Բավարար,3. Բավարար
2,3,4. Վատ,4. Վատ
3,4,4. Վատ,3. Բավարար
4,5,3. Բավարար,4. Վատ
...,...,...,...
140,119,2. Լավ,2. Լավ
141,142,2. Լավ,2. Լավ
142,143,2. Լավ,2. Լավ
143,144,1. Գերազանց,1. Գերազանց
144,145,2. Լավ,2. Լավ

In [46]:
df_selected.rename(columns={
    "Unnamed: 0" : "ID",
    "B3. Ինչպես կգնահատեք կարդալու Ձեր կարողությունը: " : "reading_score",
    "B2. Ինչպես կգնահատեք գրելու Ձեր կարողությունը: " : "writing_score"
}, inplace=True)

# Create a new column
df_selected["communication"] = ""

# Reorder columns
df_selected = df_selected[
    ["ID", "communication", "reading_score", "writing_score"]
]

In [47]:
df_selected

      ID communication reading_score writing_score
0      1                  3. Բավարար    3. Բավարար
1      2                  3. Բավարար    3. Բավարար
2      3                      4. Վատ        4. Վատ
3      4                  3. Բավարար        4. Վատ
4      5                      4. Վատ    3. Բավարար
..   ...           ...           ...           ...
140  119                      2. Լավ        2. Լավ
141  142                      2. Լավ        2. Լավ
142  143                      2. Լավ        2. Լավ
143  144                 1. Գերազանց   1. Գերազանց
144  145                      2. Լավ        2. Լավ

[145 rows x 4 columns]

In [30]:
# list(df.columns)

In [57]:
df_selected.rename(columns={
    "A16. Որքան հաճախ եք կիրառում հաղորդակցության հետևյալ ձևերից յուրաքանչյուրը:   [Ժեստերով հաղորդկացվելը]" : "sign language",
    "A16. Որքան հաճախ եք կիրառում հաղորդակցության հետևյալ ձևերից յուրաքանչյուրը:   [Բանավոր շփումը ինքնուրույն]" : "spoken language"
}, inplace=True)

In [59]:
sign_col = "sign language"
spoken_col = "spoken language"