In [10]:
import pandas as pd
from utils import age_group_label
from utils import income_band

## Practice Tasks with Synthetic Data

### Task 1

In [11]:
df_customers_dummy["age_group"] = df_customers_dummy["age"].apply(age_group_label)
df_customers_dummy

  customer  age  income age_group   income_group
0        A   22   18000     Young     Low income
1        B   35   42000    Middle  Middle income
2        C   47   72000    Middle    High income
3        D   63   95000    Senior    High income
4        E   29   25000     Young     Low income

### Task 2

In [12]:
df_customers_dummy["income_group"] = df_customers_dummy["income"].apply(income_band)
df_customers_dummy

  customer  age  income age_group   income_group
0        A   22   18000     Young     Low income
1        B   35   42000    Middle  Middle income
2        C   47   72000    Middle    High income
3        D   63   95000    Senior    High income
4        E   29   25000     Young     Low income

### Task 3

In [13]:
df_customers_dummy = pd.DataFrame({
    "customer": ["A", "B", "C", "D", "E"],
    "age": [22, 35, 47, 63, 29],
    "income": [18000, 42000, 72000, 95000, 25000]
})

df_customers_dummy

  customer  age  income
0        A   22   18000
1        B   35   42000
2        C   47   72000
3        D   63   95000
4        E   29   25000

In [15]:
df_scores = pd.DataFrame({
    "student": ["Anna", "Ben", "Chris", "Diana", "Eva"],
    "score": [95, 78, 61, 43, 88]
})

In [16]:
df_scores["pass_flag"] = df_scores["score"].apply(lambda x: "Pass" if x >= 50 else "Fail")
df_scores

  student  score pass_flag
0    Anna     95      Pass
1     Ben     78      Pass
2   Chris     61      Pass
3   Diana     43      Fail
4     Eva     88      Pass

## Practice Tasks

### Task 1

In [39]:
df = pd.DataFrame({
    "student": ["Anna", "Ben", "Chris", "Diana", "Eva"],
    "n_dependants": [4, 5, 7, 1, 3],
    "Age": [77, 55, 81, 64, 93]
})

In [26]:
def family_size_group(n_dependants):
    if n_dependants == 0:
        return "No dependants"
    elif n_dependants <= 3:
        return "Small family"
    else:
        return "Large family"

In [42]:
df["family_size_group"] = df["n_dependants"].apply(family_size_group)
df

  student  n_dependants  Age family_size_group
0    Anna             4   77      Large family
1     Ben             5   55      Large family
2   Chris             7   81      Large family
3   Diana             1   64      Small family
4     Eva             3   93      Small family

In [34]:
def senior_flag(Age):
    if Age >= 60:
        return "Senior"
    else:
        return "Not senior"

In [41]:
df.head()

  student  n_dependants  Age
0    Anna             4   77
1     Ben             5   55
2   Chris             7   81
3   Diana             1   64
4     Eva             3   93

In [43]:
df["senior_flag"] = df["Age"].apply(senior_flag)
df

  student  n_dependants  Age family_size_group senior_flag
0    Anna             4   77      Large family      Senior
1     Ben             5   55      Large family  Not senior
2   Chris             7   81      Large family      Senior
3   Diana             1   64      Small family      Senior
4     Eva             3   93      Small family      Senior